### ISSUE TITLE
Signup Restriction

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#10]
Create an option to disable Users sign-up and allow only 1 master account to exist.

If another user wants to sign-up and create a workspace, that will possible only via invites.

You can check appsmith implementation:

https://docs.appsmith.com/getting-started/setup/instance-configuration/disable-user-signup

**Comment by neon-balcony** [comment]
Hey @MichalisDBA, I am going to move this to our feature requests as it is not currently a functionality. Thanks for the feedback.

**Comment by leoborlot** [comment]
+1 

Will be good to create dashboard, but i need to close "no invited" to income!

**Comment by neon-balcony** [comment]
Hi @leonardoborlot, 
For your case I think you can just set up your app with **Share** > **Make the app public**, then share the link among your members, the app will be public to all (including anonymous users), without invitation or signup.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/118174126/202602304-9d7e1c3d-5f4e-4f33-aae5-b7b4b056c3de.png">

**Comment by leoborlot** [comment]
Sorry. I try to say, theres no one user coming in the app selfhosted without invite

#
![Screenshot_20221117-233603_Chrome](https://user-images.githubusercontent.com/20361821/202604259-cd939f65-6e12-49eb-b59e-179e166adc31.jpg)

**Comment by hybes** [comment]
How's this coming along, I see it's n Jan 2023 - is this something that's expected soon?

**Comment by neon-balcony** [comment]
Hey folks, this feature has been published with the latest image for a while, sorry for the late update 😭 

Now you can follow the steps to disable sign up:

1. Go to your workspace where Openblocks is deployed (~/workspace in my case), then `cd ./stacks/configuration`
![image](https://user-images.githubusercontent.com/118174126/215938279-13435a1a-bb9d-4366-b586-47ce4d5589ec.png)

2. edit `application-selfhost.yml`, add settings for auth as below, then set `enable-register` would help you disable user future signups.
```YAML
auth:
  email:
    enable: ${LOGIN_CHANNEL_EMAIL:true}
    enable-register: ${LOGIN_CHANNEL_EMAIL_REGISTER:false}
```
<img width="783" alt="image" src="https://user-images.githubusercontent.com/118174126/215938645-5fc315f4-741a-4393-aa88-73a454380bf6.png">

3. Save the file and restart your deployment.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/118174126/215939832-f230ab05-311a-4bcf-9b1b-1255e5024ed9.png">

**Comment by sourcebert** [comment]
If you are deploying Openblocks with Docker, you could also set the environment variable `ENABLE_USER_SIGN_UP` to `false`. See latest [docker-compose.yml](https://github.com/openblocks-dev/openblocks/blob/develop/deploy/docker/docker-compose.yaml).

**Comment by johndanek** [comment]
Would it be possible to restrict new user signups to one domain? I would like users in my org to be able to sign up easily, but no one else.

**Comment by neon-balcony** [comment]
@johndanek Good idea, but domain restriction is not enough though, we need to add mail server support combined with it to prevent hacking a non-exist email account.

**Comment by mcking230** [comment]
None of this helps me. docker environment and configuration changes dont work.
![изображение](https://user-images.githubusercontent.com/37830492/226839781-e3b374f0-5855-434e-afd4-ca5d980c85d1.png)
![изображение](https://user-images.githubusercontent.com/37830492/226838737-745eb16b-e651-48e7-ad0a-18bba91e49d3.png)
![изображение](https://user-images.githubusercontent.com/37830492/226838899-72d3f266-bbd4-46df-b8c7-24e561246d2f.png)

Of cource after changes i restarted container

**Comment by lvhuichao** [comment]
Hi @mcking230 , we apologize for the inconvenience. Openblocks now supports administrators configuring it in the Settings -> ID Providers -> ... -> Allow registration, and the old style has been deprecated.
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/33057362/227191314-d5ef7599-5b8f-47c1-974d-9f47b331c991.png">
