### ISSUE TITLE
Component-navigation submenu item "hidden" & "active" don't work?

### ISSUE THREAD

**Issue by neshorg** [openblocks-dev/openblocks#101]
When playing around with the component-navigation I've noticed that a submenu item will not be affected by its "hidden" & "active" properties. 

![image](https://user-images.githubusercontent.com/86983837/206260645-1edc35e1-f713-4c65-95c3-256836a36a01.png)

**Comment by lmx1117** [comment]
Thanks for your proposal, we will fix that asap.🫡

**Comment by lmx1117** [comment]
Hi neshorg, this issue is already solved, please check it out, and thanks again for your advice and patience. 😉

**Comment by neshorg** [comment]
Hello @lmx1117, I've just tested it and it works! 
However I think it's the other way around: Thank you for your time and effort, it is much appreciated. 😉
