### ISSUE TITLE
Woocommerce Integration 

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#102]
Create woocommerce integration like ToolJet do.

https://docs.tooljet.com/docs/data-sources/woocommerce

**Comment by lmx1117** [comment]
thanks for your proposal, we have put it on our roadmap, too😉: [https://github.com/orgs/openblocks-dev/projects/1](https://github.com/orgs/openblocks-dev/projects/1)

**Comment by YoJayz** [comment]
Hi @MichalisDBA, in the latest Openblocks [v1.1.6](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.6) release, we support WooCommerce API. Please check it out!

**Comment by MichalisDBA** [comment]
@YoJayz Thanks, i will check it out!
