### ISSUE TITLE
Feature Request: Add handling for HAL responses

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#103]
Our REST APIs respond with either `application/hal+json` or `application/problem+json`. Would it be possible to add these response types as something that OpenBlocks understands? That way I dont have to have a transformer for all the responses. 

Here is a doc from Spring about this: https://docs.spring.io/spring-hateoas/docs/current/reference/html/

**Comment by lmx1117** [comment]
Nice request🤩, so what do you expect to achieve, could you describe it more specifically, very appreciate that

**Comment by swright-eti** [comment]
When OpenBlocks gets a response from an API and that response is one of `application/hal+json` or `application/problem+json` then the response body should be kept as JSON. 

What happens now is that OpenBlocks treats the body of the response as an escaped JSON String. That means that for every response I need to have a Transformer to convert it back to JSON. If you look at the following image you can see that there is an array of devices on the path `_embedded.devices`. If I try to access that with `{{get_device_list.data._embedded.devices}}` it will fail with "undefined" because `get_device_list.data` does not contain JSON, it contains an escaped JSON string. 

![image](https://user-images.githubusercontent.com/296522/206454819-2cb644e6-7108-46ff-a158-9fd8df3a1da4.png)



Adding the ability for OpenBlocks to handle HAL responses would  extend or match the current behavior when the response is `application/json`.

**Comment by neon-balcony** [comment]
Hi @swright-eti ,

Very good point 😄 , we'll add this support in next release.

**Comment by neon-balcony** [comment]
Hey @swright-eti , a [hot fix image](https://hub.docker.com/layers/openblocksdev/openblocks-ce/latest/images/sha256-b24577f0c0baa3a067931c6717107b723a6d4d75567fe402e00b9a5f944ad220?context=explore) for this issue has been published, please update Openblocks and give us a try 😄

**Comment by swright-eti** [comment]
I have tested this and it works. Thank you.
