### ISSUE TITLE
DynamoDB Support

### ISSUE THREAD

**Issue by GeertWille** [openblocks-dev/openblocks#106]
Any plans on supporting DynamoDB like Retool does?

**Comment by lmx1117** [comment]
Thanks for your proposal, we will add this to our backlog~~

**Comment by crash7** [comment]
Hi! Do know how far is this? Do you have a beta version to try? This is the only blocker I could find for me apart from the SSO with Google.

**Comment by neon-balcony** [comment]
Hey fellas, sorry for the long waiting, a [beta version](https://hub.docker.com/layers/openblocksdev/openblocks-ce/beta/images/sha256-b3f68e27305e8993e509a79e06fa17c4abece6386ccff87accf0c5ff6870c612?context=explore) containing DynamoDB has been released, please try it out!
