### ISSUE TITLE
Auto Refresh widgets

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#11]
Because setInterval and setTimeout is disabled, would be good to create an auto refresh option to widgets.

For example we have a table that shows data from a sql query and want to continue refresh it so we can have near live statistics updates.

This or enable setInterval and setTimeout functions.

**Comment by hanshuai** [comment]
In the advanced tab of an auto-trigger query, there is an auto refresh setting. It may solve your problem.

**Comment by hanshuai** [comment]
Currently this setting is a static checkbox, we'll make it dynamic.

**Comment by hanshuai** [comment]
<img width="480" alt="Screen Shot 2022-12-07 at 4 14 42 PM" src="https://user-images.githubusercontent.com/1859205/206125231-0ba17c30-fce3-47cd-a954-1b82150b5fec.png">
We found that it's more convenient if this feature is disabled when the "period" field is invalid.
For now, you can use a sufficiently large period as a workaround.

**Comment by MichalisDBA** [comment]
@hanshuai Now it works with {{switch1.value ? "5s" : "-1"}}, it just throws an error notice in panel. I can ignore it nonetheless. Thank you.

![image](https://user-images.githubusercontent.com/68512501/206664653-065a59d0-4cdb-4911-bd51-6784053f1035.png)

**Comment by neon-balcony** [comment]
Hi @MichalisDBA ,

In latest release you can set a value less than 100 to disable periodical execution.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/118174126/207555175-a117879e-5abe-4b7b-85dd-49645989e92c.png">
