### ISSUE TITLE
Can't Control Form Submit Button via Event

### ISSUE THREAD

**Issue by johndanek** [openblocks-dev/openblocks#112]
I'm attempting to use a Form component in which the Submit button is initially disabled and becomes enabled when one of the values in the form changes. But, the button itself does not appear as an option in an event's Control Component list. Are components in Form footers excluded from the Control Component list?

**Comment by lmx1117** [comment]
Currently, you can solve it like this:
1. Set the submit button type to **default**
2. Create an event to submit the form data
3. Create a temporary state and set the init value as 1
4. Bind the **disabled** properties with {{state1.value}}
![image](https://user-images.githubusercontent.com/116335720/206624974-a10aa275-8878-4328-a636-8e0b296d595c.png)
5. Create an event for **input**(and other components in form) to set the temporary state value as 0 to enable the submit button
![image](https://user-images.githubusercontent.com/116335720/206625527-f14008aa-111f-4c1d-a35d-783d528079a1.png)

**Comment by johndanek** [comment]
Thanks! That will work.

**Comment by lmx1117** [comment]
Great! And we are considering optimizing **event** too 😉
