### ISSUE TITLE
Controlling components through query results

### ISSUE THREAD

**Issue by armx84** [openblocks-dev/openblocks#114]
Greetings
I was trying to create a Tabbed container based on query results. 
Basically I wanted to create tabs from an array.
I realized this is not possible or at least I didn't manage to do so (tried from Event handlers).

It would be nice to be able to control components like 

- Tabbed container
- Select / Multiselect / Cascader
- Tree Select

from a query result.
Any idea how high in the priority list this is?
Thanks

**Comment by lmx1117** [comment]
Actually it is supported, see
![image](https://user-images.githubusercontent.com/116335720/206958805-ee1abc12-4d15-4fb0-913d-ceda02d17a20.png)

Except for the **tab container** is not supported, others you mention can be generated similarly, btw, what is the usage scenario of the **tab container**
