### ISSUE TITLE
Question: Is it possible to export the Query Library

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#115]
I have an app that uses a number of queries from the query library. When I export the application, and then import to a different environment, those queries are not available. 

What is the proper way to handle this?

**Comment by lmx1117** [comment]
Thank you for your proposal. This is something we are discussing to improve and will be implemented as soon as possible, so stay tuned!🫶

**Comment by swright-eti** [comment]
Is it possible to dump the entire Mongo database and then import it to get around this?

**Comment by lmx1117** [comment]
Hi swright-eti, this issue is already solved, you can import/export the queries from/to JSON files in query library now, please check it out, and thanks again for your advice and patience. 😉
