### ISSUE TITLE
Feature request: programmatically change table page number

### ISSUE THREAD

**Issue by jmif** [openblocks-dev/openblocks#118]
Would be really useful to be able to programmatically change the page number of a table, or at least reset it to 1.  Use case is bringing users back to the beginning of the table when they data in the table is reloaded.

Thanks!

**Comment by lmx1117** [comment]
This is a good point of enhancement, we will support it as soon as possible, please stay tuned!

**Comment by lmx1117** [comment]
Hi jmif, this issue is already solved, we've added filterChange and sortChange events for table now, please check it out, and thanks again for your advice and patience. 🫶
