### ISSUE TITLE
Unable to run REST API Query

### ISSUE THREAD

**Issue by rcoundon** [openblocks-dev/openblocks#12]
I've set up a Data Source which is REST API and a Query in the Query Library.

However, when I run the query from the library I get the message:

```
{"code":"OK","message":"Oops! Service is busy, please try again later."}
```

Nothing is written out the output stream of: 
`docker logs -f openblocks`

Looking at the source code this seems to be a general HTTP 500 error. (NetworkMessage.500)

I can't see anything in the documentation that describes a step I've missed so I'm not sure where to go to debug this. Any pointers greatly appreciated!

**Comment by neon-balcony** [comment]
@rcoundon Hi, could you please give us some more information about your rest data source & query configuration? Code snippet or snapshot would be appreciated.

**Comment by rcoundon** [comment]
Hi - this is a screenshot (not sure how to get hold of a code snippet for it?)
<img width="964" alt="image" src="https://user-images.githubusercontent.com/9136570/201921188-d16d438a-8c4d-4cbb-9820-34f7efbe5740.png">

and this is the query

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/9136570/201921258-7124d639-c4a4-48ce-832e-70d51b72900f.png">

I've removed the actual REST API domain (and user/pass) as they're sensitive

**Comment by neon-balcony** [comment]
Problem confirmed, we're working on it now, thanks for reporting this bug.

**Comment by rcoundon** [comment]
That's great, thanks for looking into it so quickly

**Comment by neon-balcony** [comment]
@rcoundon hello, this issue has been fixed, please checkout our latest cloud-hosted version/docker image.

**Comment by rcoundon** [comment]
Thanks! I've just tried the latest and I no longer get that error but now I always get 
```
Query execution error: Password must not be null.
```
I assume it's referring to the Basic Authentication password. I've tried saving the password on the Data Source screen and via the Data Source Edit button on the Query screen but the same occurs for both

I'll raise this as a separate issue
