### ISSUE TITLE
Feature request: add the output of a Javascript query as an option for the body of REST query

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#121]
Use case: I want to do a PUT operation on a REST API using data from a form and I only want to submit what has changed from the original record. 

There is a table of records.
Clicking on a row, opens a form.
The user changes a value in the form and clicks submit. 

There is a script that figures out which fields in the form are different than the fields in the tables, and it returns a JSON object containing only those fields and values. 

How do I get that JSON object into the body of a REST API query?

**Comment by lmx1117** [comment]
![image](https://user-images.githubusercontent.com/116335720/207234064-6b9df4c7-b72a-4944-a4d5-baf3a8f075cf.png)
Are you doing this and what went wrong?🤔

**Comment by swright-eti** [comment]
I can do that. But that will send every field regardless of whether it changed or not. I want to be able to write a script to build the JSON object that will be sent to the API.

**Comment by neon-balcony** [comment]
Hi @swright-eti ,

It sounds like a [transformer](https://docs.openblocks.dev/build-apps/write-javascript/transformers) can help you with that:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/118174126/207534417-f0065968-afac-4bbe-a2db-e6b32741f332.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/118174126/207534667-5a646ca6-b845-479e-9015-dfbb93be5e41.png">
