### ISSUE TITLE
Styling (coloring) by conditional JS

### ISSUE THREAD

**Issue by neshorg** [openblocks-dev/openblocks#124]
I was wondering if it'd be possible to make (almost) every styling attribute programmable with custom JS? (just like row color in a table component)

Currently with button or other components:
![image](https://user-images.githubusercontent.com/86983837/207416899-68b7ff1c-2af4-4b26-ae4d-692403caaa1b.png)

Example of "dynamic" Row Color in a table component...and wishing to use this ability with other colors as well: 
![image](https://user-images.githubusercontent.com/86983837/207417123-e33dff75-50ed-48ac-8b3a-89eb8ef5dc87.png)

**Comment by neon-balcony** [comment]
Hi @neshorg , 

Thanks for the post, actually this is already supported in Openblocks! Check this demo below, we're using a select to control another component's background color:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/118174126/207524974-793572ed-e992-4079-bd8f-751dd1fe8b31.png">

**Comment by neshorg** [comment]
Hello @neon-balcony, I can't believe I missed this!!! 
I guess I was looking for the "JS" indicator which is why I thought it wasn't supported yet. 
Thanks a lot for clearing that up! 👍

**Comment by neon-balcony** [comment]
True! we should have provided a _JS_ indicator for that. Sorry about the misleading behavior, we'll fix it in the next release.

**Comment by lmx1117** [comment]
Hi neshorg, this issue is already solved, please check it out, and thanks again for your advice and patience.❤️

**Comment by neshorg** [comment]
Thanks @limgit, it works great!
