### ISSUE TITLE
Question: how to put an event handler on the opening of a modal?

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#125]
How do I add a handler for the opening event of a modal? I dont seem to have any option but Close. 

![image](https://user-images.githubusercontent.com/296522/207437822-65848b80-79df-4682-94af-13ee858a0e58.png)

**Comment by lmx1117** [comment]
![image](https://user-images.githubusercontent.com/116335720/207489590-b6643b40-6b0e-4861-8cba-fb66eea1a257.png)

The opening event of a modal should be added outside of the modal by other component like this👆

**Comment by swright-eti** [comment]
I dont want to open the modal, I want to handle an event when a modal opens. The only event handler available for a modal at the moment is the Close event. There should also be one for Open.

**Comment by neon-balcony** [comment]
Hi @swright-eti , 

Could you share with us about the scenario why you need the _Open_ event?

**Comment by swright-eti** [comment]
I have an edit form in a modal. When the modal opens I need to run queries to fill out the options for the Type, Model, Status, and Location ID. The Model options depend on which Type is selected. 
When the user clicks the edit button and opens the modal, the app will then know which type of device they are editing, and the app can then fetch the model options.

**Comment by neon-balcony** [comment]
Hi @swright-eti ,

Got that. I think for now the solution is to have all these data for filling the modal eagerly fetched. The benefit for that is users won't wait for the spinning of the modal, its data can be automatically updated once you change the _type of device_ in the main window.

**Comment by swright-eti** [comment]
Can you help me understand how that solves the problem for the Models, I am not seeing it. Its actually only a problem for the edit scenario (see below)

When the page loads I can fetch the Types, Locations, and Statuses. (Thats actually what I am doing now). But I dont have a practical way to load the Models since they are indexed by Type. 

One option for the lazy load of the Models would be to iterate all the Types and then do a fetch for the Models for that Type. But there are hundreds of Types, each with possibly hundreds of Models. 

But lets say that I do that. When the modal opens for an Edit action how do I set the options for the Models based on the current Type in the form?

For the edit scenario the options for Model will have to already be set because the Type is already selected. 

The create scenario is actually handled by the user selecting a type. The Type option list would have a handler that would populate the models every time a new Type is selected.

**Comment by neon-balcony** [comment]
@swright-eti What I can see that is you have a table with edit buttons, once you click on the edit button in one row, a modal with detailed information pops up, right?

Since click a button on a row will change table.selectedRow, I would assume you can write a query `getModelsByType` that triggers on table.selectedRow updates:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/118174126/207621082-9a8d601d-3d01-44f8-a31d-d8292b0af15d.png">

Then you can use the results from `getModelsByType` to fill the data in your _edit_ modal.

**Comment by swright-eti** [comment]
Got it. Thank you.
