### ISSUE TITLE
Openblocks SDK taking cloud URL instead of given baseUrl to run the query

### ISSUE THREAD

**Issue by aaron1604** [openblocks-dev/openblocks#128]
I have setup an open block as a self-hosting and created an app on it. Now I am trying to integrate that app into my personal react web app using open blocks-SDK. Everything seems to be working fine but I came across with one issue which is, If we setup an `baseUrl`, app is getting loaded successfully from self hosted openblock but the query execution still goes on cloud openblocks instead of selfhosted openblocks and thus query fails as it doesn't find the app on cloud openblocks

<img width="486" alt="Screenshot 2022-12-15 at 1 43 53 PM" src="https://user-images.githubusercontent.com/96607998/207807364-ca3a4f4c-e961-40a2-80ba-b47bc438e2f3.png">

<img width="485" alt="Screenshot 2022-12-15 at 1 44 02 PM" src="https://user-images.githubusercontent.com/96607998/207807395-f6cbaf83-d5e1-4ac3-9c01-c1fa3ac48328.png">

**Comment by sarike** [comment]
As the discussion in discord, this issue has been fixed in openblocks-sdk@0.0.23.

**Comment by aaron1604** [comment]
@sarike Yes, Checked and confirmed. Thanks a lot :)
