### ISSUE TITLE
REST API Data Source - Password must not be null

### ISSUE THREAD

**Issue by rcoundon** [openblocks-dev/openblocks#13]
I've just tried the latest docker image and with a REST API Data Source I always get the message
```
Query execution error: Password must not be null.
```
I assume it's referring to the Basic Authentication password. I've tried saving the password on the Data Source screen and via the Data Source Edit button on the Query screen but the same occurs for both

**Comment by neon-balcony** [comment]
Let me re-confirm about this issue, correct me if I'm wrong:
1. "Password must not be null." is returned by your api services
2. You assume using [Basic Authentication] doesn't transmit your password to your api service

**Comment by rcoundon** [comment]
The OpenBlocks UI shows this when I attempt to run the query:

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/9136570/201960888-9ac96905-766b-4b13-8e8d-aaddc869f9e5.png">

This is despite having populated a username and password for the Basic Authentication values

**Comment by neon-balcony** [comment]
Problem noted, I've reproduced this bug on my laptop, we'll set out solving this, thanks for reporting 👍

**Comment by rcoundon** [comment]
I'd help out but it's a loooong time since I wrote any Java, unfortunately

**Comment by neon-balcony** [comment]
Hahaha it's okay. This issue has been fixed in the latest version, check it out.

> I'd help out but it's a loooong time since I wrote any Java, unfortunately

**Comment by rcoundon** [comment]
Great, that's working now, thank you
