### ISSUE TITLE
Question: how do I query a mongo collection by _id

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#130]
In mongo shell I do this: `db.CommandLibrary.find({"_id":ObjectId("632e06ebf19464db1601302b")})`

I have a mongo connection setup in OpenBlocks, but I dont know what the Query should be.

**Comment by neon-balcony** [comment]
Hi, in Openblocks we're using [MongoDB command API](https://www.mongodb.com/docs/manual/reference/command/), and  for keywords like ObjectId/Date/Timestamp, you can use the [MongoDB Extended JSON](https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/#mongodb-bsontype-ObjectId) format.

So for your case, you can use:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/118174126/208004435-f0893f1c-24ca-409e-a1ac-db2ac57f9cf1.png">

**Comment by swright-eti** [comment]
Great, thanks.

**Comment by swright-eti** [comment]
For reference this is what I ended up with:

`{"_id": {$oid: "{{table1.selectedRow._id}}"}}`
