### ISSUE TITLE
GraphQL Connections does not work

### ISSUE THREAD

**Issue by FalkWolsky** [openblocks-dev/openblocks#131]
The connection to GraphQL can be made, however every query end up into a success-message, which contains then a error message inside. It happens for Query as also for Mutations.

Main error message is: "parse-failed" in "$.variables". "parsing HashMap failed, expected Object, but encountered String".
Seems even an empty array (?) of Variables for the GraphQL request leads into this. Eventually the mapping should be checked.
Please be aware, that Variables itself can be typed differently (String, Number, JSON)...

Thank you in advance for looking into it!

**Comment by lvhuichao** [comment]
Hi @FalkWolsky ,can you show me a screen shot with this error message and your query config detail please?

**Comment by FalkWolsky** [comment]
Hello @lvhuichao,

please find the screenshots here. Over all, even with the simplest Query i wasn't able to query via GraphQL.

<img width="564" alt="Screenshot 2022-12-15 at 22 10 06" src="https://user-images.githubusercontent.com/3671017/208405969-e80995d4-d9f7-4d57-b146-f27bdc0eccfa.png">

<img width="796" alt="Screenshot 2022-12-15 at 22 09 43" src="https://user-images.githubusercontent.com/3671017/208406693-7ebcd1a1-8bcb-4743-a6ae-3e694f9a9513.png">

My guessing is, that the Backend expect some values for Query Variables or have trouble to parse it...

**Comment by lvhuichao** [comment]
Hi @FalkWolsky ,
Please try add a header 'Content-Type=application/json' and let's see if it works out.
<img width="989" alt="image" src="https://user-images.githubusercontent.com/33057362/208573339-10fb4645-f41a-42bd-81d4-70aca31d9ac9.png">

If the error stays, have you requested this query GraphQL with Postman(or the likes), does that work?

**Comment by oekoo** [comment]
Hi! I'm running into the same issue. What can I do?

**Comment by neon-balcony** [comment]
Hey @oekoo , could you please provide a screenshot of your issue? And have you tried adding the header as described above?

**Comment by oekoo** [comment]
Sure :) 
<img width="604" alt="Bildschirmfoto 2023-01-26 um 05 30 02" src="https://user-images.githubusercontent.com/123530616/214759080-826bcffe-b18f-4db3-bbc5-2ed1d394547c.png">
<img width="614" alt="Bildschirmfoto 2023-01-26 um 05 34 35" src="https://user-images.githubusercontent.com/123530616/214759262-eed597dc-f510-4c18-89a3-ac30ee8f9837.png">


I'm using Hasura for GraphQL.

**Comment by neon-balcony** [comment]
Problem noted, we'll try to reproduce this issue with Hasura, thanks for the info.

> I'm using Hasura for GraphQL.

**Comment by lvhuichao** [comment]
Hi @oekoo , thanks for your reporting this problem. We have published a new image which has fixed it to the Docker Hub. Please pull the latest image and restart the docker container with it.
Besides above, you should update your query like this:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/33057362/215324270-ffda9a3c-d719-4635-876d-d04c7eb67f82.png">

**Comment by oekoo** [comment]
@lvhuichao Thanks for looking into this. I think removing the `query {}` part of the query will not be possible because that value could also be `mutation {}` for inserting or updating data.

**Comment by lvhuichao** [comment]
Sorry @oekoo ,i misspoke. It should be okay to keep it.

**Comment by oekoo** [comment]
I can't confirm this. If I'm running the query without the `query {}` part is resolves correctly. With the `query {}` part it is throwing the `parse-failed`error.
Checked the version (through the navigation on the bottom left): `1.1.4-fae90a0`.

**Comment by lvhuichao** [comment]
Can you give me a screenshot of your query and the response?

**Comment by oekoo** [comment]
It works. I formatted it like this:
```
{
  query {
    product {
      id
    }
  }
}
```

Instead, 
```
query {
  product {
    id
  }
}
```
is correct. Thanks for taking care of this issue.

Are GraphQL auto-suggestions already a planned feature or do I have to add an issue for that?

**Comment by lvhuichao** [comment]
Hi @oekoo , please add an issue for that.

**Comment by oekoo** [comment]
Hi! After updating to 1.1.5, I'm again unable to make a GraphQL query. 
```{
  "errors": [
    {
      "extensions": {
        "code": "validation-failed",
        "path": "$.query"
      },
      "message": "not a valid graphql query"
    }
  ]
}
```

**Comment by neon-balcony** [comment]
@oekoo Got it! Will check on this right away, sorry about the issue 😢

**Comment by neon-balcony** [comment]
Hey @oekoo, I just tried with my Hasura demo query with the latest version, and it runs fine. Can you provide your screenshots of your failed query?
<img width="818" alt="image" src="https://user-images.githubusercontent.com/118174126/218262930-f6f7a9f8-b15a-4eee-94c4-40af441b2343.png">

**Comment by oekoo** [comment]
Sure!
<img width="587" alt="Bildschirmfoto 2023-02-13 um 20 43 36" src="https://user-images.githubusercontent.com/123530616/218558753-470a95b2-06c9-4829-9de2-1877880771ce.png">
<img width="257" alt="Bildschirmfoto 2023-02-13 um 20 43 18" src="https://user-images.githubusercontent.com/123530616/218558761-76bf60aa-7664-41d6-af4d-73a0596636a6.png">

**Comment by neon-balcony** [comment]
Hey @oekoo , sorry about the issue and we've published a [beta image](https://hub.docker.com/layers/openblocksdev/openblocks-ce/beta/images/sha256-b3f68e27305e8993e509a79e06fa17c4abece6386ccff87accf0c5ff6870c612?context=explore) containing this fix and you can try it out, a formal release will be pushed around Friday this week.

**Comment by oekoo** [comment]
@neon-balcony Updated the image and it works. Thanks :)
