### ISSUE TITLE
Question: are the Event Handlers for a particular element run in sequence or in parallel

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#133]
If I have a button with the following Event Handlers:

- Control Component: update some text
- Control Component: clear a form
- Control Component: open a modal

Are they run in sequence, or in parallel?

Does that apply to all lists of Event Handlers?

**Comment by neon-balcony** [comment]
Hi @swright-eti ,

They all run in parallel, and this apply to all lists of event handlers.

**Comment by swright-eti** [comment]
Great thanks.
