### ISSUE TITLE
Editing App Javascript Reloads All Images With Each Keystroke

### ISSUE THREAD

**Issue by johndanek** [openblocks-dev/openblocks#134]
I just noticed that while writing a Javascript global function in my Openblocks app, all the images in my ListView were getting reloaded for every single keystroke and deletion in the Javascript code area. Maybe there should be some sort of debounce, or even better a Save button? Before I knew it, I had requested gigs worth of images from my S3 bucket, which is not ideal.

**Comment by neon-balcony** [comment]
Hi @johndanek 

Thanks for the report! That sounds like an intriguing issue, could you please export and upload your app here?

**Comment by neon-balcony** [comment]
Hey we just reproduced this bug, this issue will be fixed in next release😃

**Comment by neon-balcony** [comment]
Hey @johndanek , this issue has been fixed in the latest release, check it out!
