### ISSUE TITLE
Position of table toolbar can be set top or bottom

### ISSUE THREAD

**Issue by neon-balcony** [openblocks-dev/openblocks#138]
Discussions from [Discord](https://discord.com/channels/1040505649798332437/1040509755552178228/1054329973365813268):
m4rcelPL — Today at 4:41 PM
Hi, I'd like to set toolbar icon at the top of the table.

neon_balcony — Today at 5:27 PM
@m4rcelPL hey, are you referring to the whole line of toolbar and move it to the top?

m4rcelPL — Today at 5:30 PM
Yes. Searching for this is annoying if you have long list. The new user can't see it and I always have to explain it to them 😉

neon_balcony — Today at 5:36 PM
how about the pagination buttons? Stay on top or stay still

m4rcelPL — Today at 5:57 PM
Fair point, the whole bar and all the options. That would be great 🙂

**Comment by FalkWolsky** [comment]
Please ... Add to have possibility to have the Pagination anyhow on both places. That can be a boolean flag...

**Comment by lmx1117** [comment]
Hi FalkWolsky, this issue is already solved, now you can set the position of the Toolbar and Pagination to the bottom/top or just hide it, please check it out, and thanks again for your advice and patience. 🫶

**Comment by neon-balcony** [comment]
Mark as closed since feature supported in image version v1.1.3.
