### ISSUE TITLE
Ability to pass arguments to queries / js functions at the event handler

### ISSUE THREAD

**Issue by a-c-m** [openblocks-dev/openblocks#14]
Much like the excellent module system, it would be very powerful if you were able to pass args to functions or queries.

This functionality for example, would allow for easy integration with any analytics 3rd party, tracking button or other clicks. I imagine it would open a wide number of other use cases as well.

**Comment by neon-balcony** [comment]
Hi, could you please give us one specific case using arguments for queries at event handler? We want to find it out whether there is already a solution to your scenario.

**Comment by a-c-m** [comment]
Imagine you had a analytics service like segment. E.g.

`analytics.track({
   userId:'f4ca124298',
   event: 'Signed Up',
   properties: {
     plan: 'Enterprise'
   }
 });`

You could then have a single `track` JS function (assuming the Lib and setup is already done), which accepts 2 arguments  E.g.
EventArg
PropertiesArg

so you have

`analytics.track({
   userId:'{{currentUser.analyticsID}}',
   event: '{{EventArg}}',
   properties: {{PropertiesArg}}
 });`

Allowing you to call this single is function in lots of places passing what you need, instead of having lots of instances of the same thing with just different properties.

**Comment by neon-balcony** [comment]
Okay I see, currently we're working on providing **Run JavaScript** in event handler(which will be released soon), I think your case can take use of this function:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/118174126/202168451-62b2706d-f0ed-4dde-a6d9-456e932b48c7.png">

**Comment by a-c-m** [comment]
YES! That would 100% cover my use case. Thank you. 

But I also think you may want to consider the wider solution of allowing bindings/params being defined on all events (queries, too), then exposed on the invocation screen (like modules, or like https://docs.budibase.com/docs/rest-bindings) as it would be even more flexible and user-friendly and allow for more reusable queries etc.

**Comment by neon-balcony** [comment]
Hi, a new version has been released, check **Run JavaScript** out with our latest cloud version/docker image.

For the bindings/params of queries, actually we're already re-examining the whole query/API thing and considering that backend queries can be orchestrated and can be reused everywhere with arguments. Thanks for the feedback.

**Comment by a-c-m** [comment]
Tested it, works really well. The only additional ask would be a variable for the parent calling the js to allow for `alert('the button with text ' + caller.text + ' was pressed');` But its not critical.

**Comment by neon-balcony** [comment]
this "alert" functions is already supported, try use 
```JavaScript
message.info("button clicked", { duration: 10 })
```
in your JS script. We'll write documentation for that soon.

**Comment by a-c-m** [comment]
The alert was just a trivial example, the point i was trying to show was the ability to have the context of the element which triggered the event, in the event JS/Query. So you could use a single JS function/Query and change its behaviour based on the button that was pushed

selectedImage [ DROP DOWN SELECTOR \/ ]

Download as buttons [[SVG]] [[GIF]] [[JPG]]

They then trigger 
`downloadAsFileType(selectedImage.text, eventCaller.text);` so you only need a single function, instead of needing a JS script or func/query per button.

**Comment by neon-balcony** [comment]
Okay I see, we'll look into that, thanks as always.
