### ISSUE TITLE
Table performance issue

### ISSUE THREAD

**Issue by neon-balcony** [openblocks-dev/openblocks#151]
From Discord:

jmif — 12/24/2022 2:05 AM
hi all, I've got an app that we've been using for about 3 weeks with no issues and a couple days ago it started hanging when it was loading (chrome pops up a window saying "this tab is stuck, do you want to wait?".  it loads a decent amount of data into tables, but the amount of data that it loads hasn't changed nor has the page configuration, so I think this may be due to a recent change.  what's the best way to report something like this?

jmif — Yesterday at 12:41 AM
just a bit more context, if i limit the amount of data returned in they query it doesn't hang, but as i mentioned this just started happening and there were no changes in the config of the app or the amount of data returned in the past few weeks.

**Comment by MichalisDBA** [comment]
I attach 2 screen records.

I use mysql database and fetch 1000 rows with many collumns.

You can see that with version 1.1.2 the table is fetching and paginating the data much faster that version 1.1.3. Also 1.1.2 is less resource intensive in memory.

1.1.2 Screen record:
![1 1 2](https://user-images.githubusercontent.com/68512501/211490354-5f922e5d-157d-45cb-8418-2dae85c456b2.gif)


1.1.3 Screen record:
![1 1 3](https://user-images.githubusercontent.com/68512501/211490414-07df5c33-9414-41b4-a7ae-210101480e04.gif)

**Comment by Simonaaaa-C** [comment]
This is now improved in v1.1.4, please check it out.

**Comment by MichalisDBA** [comment]
@Simonaaaa-C 

Yes now the table has improved a lot. It is not yet the same performance as version 1.1.2 but it's getting closer. 90% same performance as version 1.1.2 let's say.

Thank you
