### ISSUE TITLE
Java Backend openblocks-server won't compile

### ISSUE THREAD

**Issue by FalkWolsky** [openblocks-dev/openblocks#157]
In the current state (cloned today), the Backend Java won't compile.

server/openblocks-server/src/main/java/com/openblocks/api/home/FolderApiService.java trows error.
Line 263 - "Type mismatch: cannot convert from Mono<Object> to Mono<Tree<T,Folder>>Java(16777235)"

Please have a look.

**Comment by lvhuichao** [comment]
Hi @FalkWolsky , i just try to compile and it runs successfully.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/33057362/210033928-335aef0d-3649-49b2-8750-ae871c3260c7.png">

Can you provide these information for me:
1. current commit id
2. java version
3. maven version
4. screenshot of the compile error

**Comment by FalkWolsky** [comment]
Commit ID b09f2e03
OpenJDK 17.0.2 (OpenJDK Runtime Environment Temurin-17.0.2+8, 64-Bit Server VM)
Maven 3.8.6

<img width="766" alt="Screenshot 2022-12-29 at 20 53 59" src="https://user-images.githubusercontent.com/3671017/210074981-3abbee2a-36fb-47ec-bd15-8e8f9d642605.png">
<img width="1101" alt="Screenshot 2022-12-29 at 20 53 48" src="https://user-images.githubusercontent.com/3671017/210074985-1d39266b-8ead-4536-816c-cf78e473aeeb.png">

**Comment by lvhuichao** [comment]
Have you executed the command "mvn clean compile"? Does that work?

**Comment by FalkWolsky** [comment]
Hmm. Despite the displayed type error, the build did go through and successfully compiled.
So, i recommend to have a look, since the type mismatch can cause trouble at runtime?
The method buildFolderTree() expect to return Mono<Tree<T,Folder>> (which makes sense) - but the inner function call returns a Mono<Object>. 

But, the build was made and we can close the issue.
