### ISSUE TITLE
Self Hosting an OpenBlocks App

### ISSUE THREAD

**Issue by Rutvik-Trivedi** [openblocks-dev/openblocks#160]
Hi. Very new to frontend development and open blocks. I wanted to know whether it is possible to download the app as code and self-host an OpenBlocks created app? If not, will there be any future prospects? Thanks.

**Comment by neon-balcony** [comment]
Hey @Rutvik-Trivedi ,

Welcome to Openblocks and thanks for the post! Openblocks is a low-code platform for those apps you built to run on. When you export/download an app, it's a JSON that are readable and understandable by Openblocks, and to which we usually would refer as a **DSL** file. So for an aPaas provider like Openblocks, it's impossible to export/download the app as a raw HTML/JS/CSS source code bundle

**Comment by Rutvik-Trivedi** [comment]
Thanks @neon-balcony
So, I have absolutely zero knowledge about frontend development. Considering this, would it be possible, in any way, to get source code of my designed app on Openblocks? May it be using some third party provider or in any manner? Or maybe you could suggest some way in which I can have an app build by a similar drag and drop format and export it? Thanks for the prompt reply.

**Comment by neon-balcony** [comment]
@Rutvik-Trivedi Sorry, for aPaaS providers like Openblocks you cannot export or generate the source code for your design app. You have to depend on the platform to get your apps running.

**Comment by Rutvik-Trivedi** [comment]
Thanks @neon-balcony
That was helpful. Closing the issue now
