### ISSUE TITLE
Custom rule fails for input components

### ISSUE THREAD

**Issue by neon-balcony** [openblocks-dev/openblocks#161]
From Discord:
Moultrex — Today at 6:11 PM
Something is definetely wrong with custom rules OR i am doing something very wrong. Please look at the screen recording
![image](https://user-images.githubusercontent.com/118174126/210351103-60e6d39c-c8a5-4f08-895d-1148b66a3544.png)

**Comment by MichalisDBA** [comment]
I attach the screen record

![custom_rule](https://user-images.githubusercontent.com/68512501/210351611-270703f7-bdad-4753-b954-05a5a839bb0e.gif)

**Comment by neon-balcony** [comment]
Hi @MichalisDBA , this issue has been fixed in the latest image, please check it out.

**Comment by MichalisDBA** [comment]
@neon-balcony Yes now it works. Thank you.
