### ISSUE TITLE
Regex does not recognise $ character at the end

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#162]
Regex does not recognize dollar sign ($) to anchor a regular expression to the end of the source text.

You can not validate explicit patterns.

![image](https://user-images.githubusercontent.com/68512501/210353123-c968bca9-a0bc-425c-a5e2-8aacfca5d61d.png)

**Comment by neon-balcony** [comment]
Hey @MichalisDBA , this issue has been fixed in the latest image, please check it out 😄

**Comment by MichalisDBA** [comment]
@neon-balcony Yes now it works. Thank you!
