### ISSUE TITLE
Inside docker with DNS service discovery this is a valid endpoint.

### ISSUE THREAD

**Issue by publicarray** [openblocks-dev/openblocks#164]
![image](https://user-images.githubusercontent.com/5497998/210554208-c276a3bd-f5f9-48d1-903e-50531e583fdb.png)

**Comment by neon-balcony** [comment]
Hey @publicarray ,

Just to make sure, it seems that you're using a customized api domain named **my_api** with its DNS specified? And this domain works well in your browser?

**Comment by publicarray** [comment]
Sort of yes. I have a docker compose file with the container name (in this contrived example) my_api. If i use another docker service/container also specified in the compose file (or docker network) I can resolve the ip by the container name aka my_api. This is well documented by docker and if i remember correctly is called dns service discovery. 
I don't want to use IPs as they can change on restart

**Comment by publicarray** [comment]
To answer your question yes the same would be true if I created a entry in my host file locally and had an API endpoint

**Comment by neon-balcony** [comment]
Thanks for the clarification, it sounds like we need to update the URL regex checking logic here. I believe this issue can be fixed in next release, we'll get you informed then😃

**Comment by publicarray** [comment]
Yea it's a common mistake I've reported similar issues to other projects before. regex only work well with some assumptions. Thanks for getting a fix in place.

**Comment by Simonaaaa-C** [comment]
Hi, we have optimized URL validation for REST API data source. Please check and update to the latest version v1.1.4. Thanks for your advice and patience!

**Comment by publicarray** [comment]
Thanks guys for the update!
