### ISSUE TITLE
Google Single Sign On

### ISSUE THREAD

**Issue by crash7** [openblocks-dev/openblocks#169]
Hi! 
Openblocks looks really nice! Would be more than happy to contribute in the future (at least on the JS part) if I get more familiar with it.

I see that you support google sign-in on the cloud solution, but doesn't seem to be available on this repository. Are there any plans to add that? Since you have that already implemented for both github and google, it would be great if you could expose env variables that we can use to configurate a custom google project for internal apps.

**Comment by neon-balcony** [comment]
Hey @crash7 , 

Thanks for the post! We're planning to add Google sign in, the issue for now is that we don't have a nice/friendly UI to for our Social login configuration setup (we're currently using YAML file to configure Google SSO on cloud). But we're considering push the _raw version_ first (maybe late this month), and add the configuration UI some time later. 😄

**Comment by crash7** [comment]
Hi @neon-balcony! A raw version would be fine for me! Do you think you will push it any time soon?

**Comment by neon-balcony** [comment]
Hey @crash7 sorry this is not ready for now and I think it should be ready around Feb 10th (which is our next iteration release time)

**Comment by crash7** [comment]
Hi @neon-balcony! I see that you have published a new release 🎉 - is the raw SSO available to use? I have no problem on doing a configuration using environment variables!

**Comment by neon-balcony** [comment]
@crash7 Sorry we're still working on providing Google & Github integrations along with a graphical interface to set up them. This is a big change in our code and so we're a little bit delayed. But I'm pretty sure it will be released at next version (or before it, shipped in a beta version).

**Comment by mingfang** [comment]
would the new feature work with generic oauth?

**Comment by crash7** [comment]
@neon-balcony if you think there is a way to contribute to it, I would be happy to do it. I'm waiting that feature in order to use it :)

**Comment by indramalav** [comment]
Hi, @neon-balcony I see that you have published a new release - is the Google SSO available to use now?

**Comment by SvV-CWinJS** [comment]
Hi
Thanks for the ongoing work.
I too am wanting to use this feature, so looking forward to a release with it 😃

**Comment by neon-balcony** [comment]
Hey folks, please check out our latest image! You should find Google/GitHub login here:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/118174126/224934334-cfec0462-6244-4f6d-9915-5407a72410a8.png">
