### ISSUE TITLE
Openapi Import for datasources

### ISSUE THREAD

**Issue by unclesamwk** [openblocks-dev/openblocks#172]
Hey guys,

would it be possible to import a JSON file from openapi /like swagger to use all datasources directly?

Otherwise stay on the ball.

Greetings
Sam

**Comment by neon-balcony** [comment]
Hey Sam,

Unfortunately this is not supported yet, but that sounds like a cool idea. Just import the JSON and we can generate all queries base on that, right? I'll add it to our backlog, thanks for the proposal!
<img width="622" alt="image" src="https://user-images.githubusercontent.com/118174126/211451907-e72be9b8-030d-4ee8-adce-608c7517055a.png">

**Comment by hanshuai** [comment]
Fixed
