### ISSUE TITLE
Throttle at a Button not working accordingly

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#179]
When you set up throttle at a button component that runs a query, let's say 5s, if you spam press that button before 5s mark, the query would run 2 times.

The expected behavior is to not run second time until 5s mark and then you have to press the button again after 5s mark to run the query again.

I attach a screen record.

![throttle](https://user-images.githubusercontent.com/68512501/212005246-f4b97289-2ba0-46a7-8ce3-aec0a99354f0.gif)

**Comment by Simonaaaa-C** [comment]
Hi! This is now fixed and verified. Please check and update to the latest version v1.1.4. Thanks for your advice and patience!

**Comment by MichalisDBA** [comment]
@Simonaaaa-C 

Yes now it works as expected. Thank you.
