### ISSUE TITLE
Fixed height text box not expanding 

### ISSUE THREAD

**Issue by jmif** [openblocks-dev/openblocks#187]
I have a fixed height text field (ie height is set to fixed, not auto), but the text field itself does not expand to fill the height of the container:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/1000442/212574257-d6f96b2d-f881-4fec-a9e2-b09308257cec.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/1000442/212574268-0a23cc6a-f68d-4681-9863-eb28a811109a.png">

**Comment by lmx1117** [comment]
Hi jmif, thanks for your proposal, we will improve that soon.

**Comment by Simonaaaa-C** [comment]
Hi! This is now fixed. Please check and update to the latest version v1.1.4. Thanks for your advice and patience.
