### ISSUE TITLE
Bug: cannot detect change value in table to EMPTY cell

### ISSUE THREAD

**Issue by Simonaaaa-C** [openblocks-dev/openblocks#192]
From Discord:
https://discord.com/channels/1040505649798332437/1040509691433857036/1065016128222531614

m4rcelPL — Today at 5:13 AM
Hi 👍 great job! But how to detect change value in table to EMPTY cell? 🤔
![image](https://user-images.githubusercontent.com/102499458/213065855-a4e7f54f-d0d6-4123-8614-9f2a259e482a.png)

**Comment by neon-balcony** [comment]
Issue close as fixed in latest hot fix.
