### ISSUE TITLE
openblocks/api/home/FolderApiService.java - Type mismatch

### ISSUE THREAD

**Issue by FalkWolsky** [openblocks-dev/openblocks#195]
server/api-service/openblocks-server/src/main/java/com/openblocks/api/home/FolderApiService.java
   
```
private <T> Mono<Tree<T, Folder>> buildFolderTree(String orgId) {
        return folderService.findByOrganizationId(orgId)
                .collectList()
                .map(folders -> new Tree<>(folders, Folder::getId, Folder::getParentFolderId, Collections.emptyList(), null, null));
    }
```
There is a type mismatch in line 264. "Function Delivers Mono<Object> but return type should be  Mono<Tree<T,Folder>>

**Comment by lvhuichao** [comment]
Hi @FalkWolsky ,i try to reproduce this error, but it looks like good in my IDE. So what kind of IDE do you use? And have you tried to compile the project with maven?
And if you just want to fix it, try inlining this method into where it's called or converting the "T" to "Object".

**Comment by FalkWolsky** [comment]
Thank you @lvhuichao. Converting the "T" to "Object" did work well. Can you take this change into the sources?
I use VS Studio Code IDE and Maven.

**Comment by lvhuichao** [comment]
Ok, i will push it soon and please stay tuned.
