### ISSUE TITLE
Table - column type [Date Time] format doesn't seem to work

### ISSUE THREAD

**Issue by neshorg** [openblocks-dev/openblocks#201]
Hello, 

It seems that version 1.1.4 introduced something strange when using a custom format in the Date Time column type in a table.

When filling in the same format as the default placeholder suggests, it works fine:
![image](https://user-images.githubusercontent.com/86983837/213547707-a38240c0-0d40-482e-ad47-028c279b8512.png)

However, when modifying this into a custom format, the date referenced value changes and goes to 0, thus giving year 1970 and so on:
![image](https://user-images.githubusercontent.com/86983837/213548406-8c5e5501-a5bd-4482-abc8-cb4df85e912d.png)

During writing of this issue, I discovered it jumping to a different value after another custom format:
![image](https://user-images.githubusercontent.com/86983837/213548639-9592a3b3-7a3a-4b2b-903a-4abaefec426e.png)
 
All of this seemed to work fine in version 1.1.3. 
Can anyone reproduce and confirm this behaviour?

Btw: I've tested this on the [cloud ](https://cloud.openblocks.dev/) and locally with docker. Both give the same behaviour.

**Comment by neon-balcony** [comment]
Hey @neshorg ,

Thanks for reporting this bug, it should be fixed in latest release, please kindly upgrade Openblocks to check it out!

**Comment by neshorg** [comment]
Hello @neon-balcony,

It took some time, but I was finally able to test this out...and now indeed it works with that last release. Thanks!
