### ISSUE TITLE
Use for customer facing apps

### ISSUE THREAD

**Issue by fullmetal-fred** [openblocks-dev/openblocks#202]
Hey! Openblocks is sick! I'd love to use it to build customer-facing web apps, but need to understand how pages are authenticated. Is there an example / reference implementation of a customer-facing app with authn? Imagine I built it on Xano or similar so I brought my own backend & user database via Rest API or Database backend. 

Thanks!

**Comment by neon-balcony** [comment]
Hey @avfuturist , 

Thanks for the post! What kind of authn are you using? Normally you can have your customers use the form login or Google/Github login (which would be added soon). But if you're using some enterprise logins (LDAP, CAS, OAuth 2.0, etc.), please let us know.

**Comment by fullmetal-fred** [comment]
The idea would be to leverage an IDP like Auth0, FusionAuth, etc. But in order to use this for the app I'm building I'd want granular custom access controls within each app.

**Comment by neon-balcony** [comment]
@avfuturist Sorry for the late response, currently we do support LDAP/CAS/OAuth 2.0(OIDC) for our enterprise editions, and the login process would be exactly the same as you do login with Google/Github on Openblocks cloud.
