### ISSUE TITLE
[Bug]:  Table with working edit in cell doesn't work when is in "Navigation". The save button does not run query.

### ISSUE THREAD

**Issue by lmx1117** [openblocks-dev/openblocks#203]
From [discord](https://discord.com/channels/1040505649798332437/1040509691433857036/1065735678605922344)
m4rcelPL — Today at 4:53 AM
I confirm, it works. But i have new problem, the same table with working edit in cell won't work when is in "Navigation" component. The save button does not run query. 😦

**Comment by neon-balcony** [comment]
Close as issue fixed in latest release version.
