### ISSUE TITLE
[Feat] Confirmation prompt

### ISSUE THREAD

**Issue by hialvaro** [openblocks-dev/openblocks#208]
Allow an option to set a confirmation prompt before triggering an event. 

On the Event action setup, a checkbox with a "Confirmation prompt". Whenever that event is to be triggered, prompt the user for confirmation. This would be great as it would save from missclicks without using complex js in each event I want this.

**Comment by neon-balcony** [comment]
Hey @hialvaro for now we do support adding a confirmation dialog for queries set with `Manually triggered`. Please give it a try 😄 
<img width="967" alt="image" src="https://user-images.githubusercontent.com/118174126/214597077-8cd68b51-fca6-439c-aeeb-94febf68f8db.png">

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/118174126/214597295-a4399d9f-06f0-4f6c-a62a-08db3f63e7ed.png">

**Comment by hialvaro** [comment]
Awesome, that's what I was looking for!
