### ISSUE TITLE
More table controls (e.g. side scrolling)

### ISSUE THREAD

**Issue by a-c-m** [openblocks-dev/openblocks#21]
The tables are nice, but in many cases the data will be many columns wide. 

Currently, it tries to squeeze all the columns into the space provided, never allowing for horizontal scroll - which becomes unreadable very quickly.

Can we have horizontal scroll as a toggle on tables? Probably defaulting to true.

**Comment by neon-balcony** [comment]
Hi, actually this is already supported, check this out
![table-horizontal-scroll](https://user-images.githubusercontent.com/118174126/202193370-87dac3ef-b0e9-4bc7-ac58-efc83f578719.gif)
