### ISSUE TITLE
[Bug] MySQL Delte Row via GUI-Mode not Working

### ISSUE THREAD

**Issue by Daniel-CS-Team** [openblocks-dev/openblocks#213]
Problem:
A Query configured in GUI-Mode to delte a Row in a MySQL Database does work in Edit-Mode for the App, but not in View Mode.
If the Query is configured in SQL-Mode with correct MySQL Syntax, it works fine.

I assume, there is a bug in the translation from GUI-Mode to actual SQL.

**Comment by neon-balcony** [comment]
Hey @Daniel-CS-Team , thanks for bringing up this issue. 

I notice that you're mentioning it works fine in Edit Mode but not in View Mode, I was wondering can it be a [release management](https://docs.openblocks.dev/build-apps/version-and-release-management#release-management) issue? Have you ever published this app and forgot to publish it again? 

If this is not the case, could you please export the app and share it with us?

**Comment by neon-balcony** [comment]
Hey @Daniel-CS-Team , this issue has been fixed in latest image, please kindly upgrade to the latest version and check it out.
