### ISSUE TITLE
Table Enhancements

### ISSUE THREAD

**Issue by gboxxx** [openblocks-dev/openblocks#223]
Awesome tool! Out of all the low-code options, this was the only one that didn't take 140 hours to get running in Docker. 

Some enhancements for tables: 

**Column Types**
- Boolean
- Image
- Select (ability to perform action for each)
- HTML
---
- Auto fit cell width to content 
- Option to auto drop hidden columns to bottom of the ordering list or a toggle to display only active columns (ex: Woocommerce products have something like 85 data points, many don't need to be seen by end-users. It's annoying to scroll the list to find a column to edit, or to rearrange them all one by one). 
  - Click on column Header to open that column's settings

Is there a roadmap anywhere? It'd be great to create a place for people to share projects or examples - love the **clone** ability!

**Comment by lmx1117** [comment]
Thanks for your appreciation, this is our roadmap, please check it out [https://github.com/orgs/openblocks-dev/projects/1](https://github.com/orgs/openblocks-dev/projects/1)

And could you be more specific about the Boolean, Image and HTML column types, what features you want to reach out? Also we already have the image column type, do you have any good ideas of enhancement?

**Comment by gboxxx** [comment]
Forgot to delete image from my list after realizing that! 

For HTML, I have API responses that return HTML like `<b> `, '<span>', etc. I'm less concerned with rendering the HTML as I am with it being stripped so as to view the text easier. Retool does this. 

Select would be for when manually adding columns (at least my particular use case). The goal is to give users the ability to select from a dropdown (whether manually created or dynamically from an API response) to perform various actions via event handlers. 

Boolean would render TRUE/FALSE cells with a checkbox or empty box. When scrolling through a giant list of results, it's easier on the eyes (in my opinion) to spot this vs. deciphering TRUE/FALSE.

Also realized a little extra step that may not be necessary for cloning projects. For those of us who are self-hosted, to clone someone else's project (like your IMDB temporary state pagination), we have to create account/login, and then export JSON. Change **CLONE** button to **EXPORT** with option to export to account or JSON would be cool. Just a nitpicky thought.

**Comment by gboxxx** [comment]
Just adding on another request another – Let cells accept hex codes to color text based on cell value. Example:
` {{ currentCell == 'instock' ? "#EF463E" : "#00000" }}`

Current behavior simply replaces "instock" with "#EF463E".

**Comment by lmx1117** [comment]
And last few questions🙌

1. will this solve your Boolean column types use case？
![image](https://user-images.githubusercontent.com/116335720/215952543-464d4783-a64c-4e29-a9e2-3c9340d0dc0f.png)

2. The return value of the trinomial operator like this may be a bit problematic, but I understand that you want to set the text color by determining the value of the currentCell, so whether adding a CSS setting like this would solve your problem
![image](https://user-images.githubusercontent.com/116335720/215957489-6bb8fbe6-08c3-436b-98e4-3bbe1342ed17.png)

3. and for the select in table, I'm still a little confused, if you want to add a new column why is a single select component not help

**Comment by gboxxx** [comment]
1. It could work now, yes. 
2. Not sure how I'd go about doing that so it dynamically changes the color. 
3. This may help explain: 
![image](https://user-images.githubusercontent.com/96701009/216031087-a8ee78b5-509c-4e6c-8751-587d0b7c45bd.png)

**Comment by lmx1117** [comment]
Hi @gboxxx in [v1.1.5](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.5) we have supported Select in table, and as for html maybe you can use the Markdown column type, please have a try
