### ISSUE TITLE
Accessing member data

### ISSUE THREAD

**Issue by zuroma999** [openblocks-dev/openblocks#226]
Unless I'm missing it, it looks like it's impossible to access member data, except the current user in the global "currentUser" object?

It would be great if user management was moved to the database, so it could be maintained by whatever database frontend being used, but mainly to be able to be queried in apps.

For example, if we have a project management app, to assign someone a task, we'd need a query to fetch all the members' names and ids, so a drop down could be populated.

As it is now, we'd have to create our own user management table and keep it in sync every time someone logs in.

**Comment by ggbond2077** [comment]
Is this what you need?

![image](https://user-images.githubusercontent.com/20850558/215933343-46648b90-ac31-42c9-9b4e-49321cf35304.png)

**Comment by zuroma999** [comment]
Awesome! That's exactly what I need. I was mainly building queries on the Query Library screen, so I never saw that data source. I'll play around with it. Thanks!

**Comment by zuroma999** [comment]
Only minor issue is it doesn't seem to be returning their emails:

<img width="132" alt="Screenshot 2023-01-31 at 7 02 45 PM" src="https://user-images.githubusercontent.com/49953523/215935013-792415ed-9505-4211-82df-3bd1ae7fda9f.png">

**Comment by neon-balcony** [comment]
Hey @zuroma999 thanks for posting the issue, it will be fixed in next release (around Feb 9th) 😄 

> Only minor issue is it doesn't seem to be returning their emails:
> 
> <img alt="Screenshot 2023-01-31 at 7 02 45 PM" width="132" src="https://user-images.githubusercontent.com/49953523/215935013-792415ed-9505-4211-82df-3bd1ae7fda9f.png">

**Comment by neon-balcony** [comment]
@zuroma999 Please check out latest image, now you should find user's login email
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/118174126/216057038-2bcb893f-53d1-4026-86eb-81b3ce084b6e.png">

**Comment by zuroma999** [comment]
Thanks, will update. Awesome app!
