### ISSUE TITLE
Seeking solution for separate frontend and backend deployment on different hosts

### ISSUE THREAD

**Issue by meong1234** [openblocks-dev/openblocks#227]
Hello, I was wondering if it's possible to separate the deployment of the frontend and backend into different hosts? the Idea is to deploy the frontend to CDN (AWS CloudFront) and expose the API service publicly. Any suggestions or advice would be appreciated. Thank you!

**Comment by jerry-goodman** [comment]
Yes, you can build the frontend with the following code.
```
cd client
yarn --immutable
REACT_APP_API_HOST=YOUR_BACKEND_HOST
REACT_APP_ENV=production \
REACT_APP_LANGUAGES=en \
yarn build
```
For more information, please refer to [deploy](https://github.com/openblocks-dev/openblocks/tree/develop/deploy/docker).

**Comment by meong1234** [comment]
@jerry-goodman nice.. thanks
