### ISSUE TITLE
Firebase / Firestore support

### ISSUE THREAD

**Issue by devth** [openblocks-dev/openblocks#23]
Amazing project! Would love to see deep Firebase integration. Seems very philosophically aligned.

**Comment by neon-balcony** [comment]
Sure, it's already on our agenda, stay tuned!

**Comment by agaitan026** [comment]
👍

**Comment by a-c-m** [comment]
Would push for support / compatibility with [supabase](https://supabase.com/)

**Comment by skybird-dev** [comment]
yes, firebase realtime database would be excellent

**Comment by YoJayz** [comment]
Hi all, in the latest Openblocks [v1.1.6](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.6) release, we support Firebase API. Please check it out!
