### ISSUE TITLE
Question about OpenBlocks AMI Image Generation

### ISSUE THREAD

**Issue by meong1234** [openblocks-dev/openblocks#232]
I am curious about how the OpenBlocks team generates AMI images. I am planning to create a custom one without Nginx and frontend components since my team thinks it's best to put these components on a CDN. Can you provide any insights or information on this process? Thank you.

**Comment by jerry-goodman** [comment]
Hi, @meong1234. Glad to see your issue again, we currently provide an all-in-one image, which includes frontend, backend, MongoDB, etc. It can be stateless. You can use this image as a service to handle your backend requests from the browser. It is not a good solution but it is the one that works now. Of course, you can also build a custom image by yourself. We provide a way to build each sub-service individually.  For more information, please refer to [docker](https://github.com/openblocks-dev/openblocks/tree/develop/deploy/docker).

**Comment by meong1234** [comment]
Thank you @jerry-goodman for the valuable information. I will definitely take a closer look

I am currently using the AMI (all in one), May I inquire about the availability of the version 1.1.4 AMI?

**Comment by jerry-goodman** [comment]
Ok, I will release version 1.1.4 on AWS AMI later.

**Comment by meong1234** [comment]
Thank you @jerry-goodman
