### ISSUE TITLE
Table Columns Fixed Width Custom Values

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#234]
When you have a table with many columns and want to make the columns fixed width you have to click and drag the column to expand. If you have many columns this is getting alot difficult.

Introduce a field when you make the column width fixed to define the width in pixels (px) or percentage (%) so that you do not have to click and drag columns to adjust to your needs.

Example like the screenshot bellow

![image](https://user-images.githubusercontent.com/68512501/216281477-15be3406-7fca-4e44-8acf-bcca8227f5b2.png)

**Comment by lmx1117** [comment]
Thank you for your suggestion, this is a very good improvement point, we will implement this feature, also, do you need a function to fix all columns width with one click

**Comment by MichalisDBA** [comment]
@lmx1117 Yeah that would be great. Thanks

**Comment by lmx1117** [comment]
Hi @MichalisDBA this feature has already supported, please check😉

**Comment by MichalisDBA** [comment]
Just tried it. Simply awesome. Thank you OB team!
