### ISSUE TITLE
How to run openblocks behind proxy?

### ISSUE THREAD

**Issue by nemulos** [openblocks-dev/openblocks#24]
I would like to test this but wondering if I can run openblocks behind a proxy, specifically the REST API query using the Docker image. 

Thanks.

**Comment by hanshuai** [comment]
It should be no obstacle to runing behind a proxy, what issues are you encountering?

**Comment by nemulos** [comment]
Do I need to pass specific environment variables to openblocks docker container to setup the proxy?  See Budibase example [here](https://docs.budibase.com/docs/running-budibase-behind-company-proxy).
