### ISSUE TITLE
Granular permission control on components

### ISSUE THREAD

**Issue by zuroma999** [openblocks-dev/openblocks#240]
Unless I'm missing an easier way to do it, I'm having to repeat code in all my apps to go through and set permissions to hide/disable individual components on page load.

It would be great in there was a built-in way to handle this, and the Disabled & Hidden fields on components could use it.

Right now I have to do something like this in all my apps:

```
const $g_v='Volunteer';
const $g_d='Developer';

// disable clip update button
clipUpdateBtnDisabled.setValue(belongsTo([$g_v]));

// disable override button
forcedOverrideBtnDisabled.setValue(!belongsTo([$g_d]));

// returns true if they belong to any matching groups
var $group_names=null;
function belongsTo($desired_groups) {
  if (!$group_names) $group_names=currentUser.groups.map(el => el.groupName);
  return $desired_groups.some(r=> $group_names.indexOf(r) >= 0); 
}
```

**Comment by neon-balcony** [comment]
Hey @zuroma999 I guess you're using temporary states with a JS query in above code, have you considered just using [transformers](https://docs.openblocks.dev/build-apps/write-javascript/transformers)? In that way you don't need to copy code around and set them in the property pane can be more intuitive.

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/118174126/216876491-eec6b505-a284-4b7e-a231-7eaa2895bbd4.png">

**Comment by zuroma999** [comment]
Thanks for the tip! That simplifies it in some cases. Other cases I need temporary states used for disabled buttons because I need to run a query first. I'll make some code more general and move it to a module method/query/output.
