### ISSUE TITLE
REST Query input parameter serialization exception

### ISSUE THREAD

**Issue by Peterkrol12** [openblocks-dev/openblocks#243]
I encountered an issue with a REST Query input variable and its serialization.

I'm executing a POST request to Cognito to retrieve a `IdentityId` for a given `AccountId` and a `IdentityPoolId`. To obtain the `IdentityId`, the request has to be supplied with a `identity_token` (which can be retrieved with [Cognito oauth2 grants](https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/)).

I have a variable `identity_token` configured as input variable for the POST request. The `identity_token` variable is used within the `JSON` body of the request. While hovering over the body, the popup shows the correct body with the `identity_token` variable filled in. However, when executing the request, the following error is returned: `{"__type":"SerializationException"}`. After this, I tried copying the contents of the body hover popup and pasting it into the same request, but using a HTTP client ([Insomnia](https://insomnia.rest/)). This worked like expected, no serialization exception returned from `AWS`.

So I decided instead of using the `identity_token` input variable, just straight up pasting the value of the variable into the `JSON` body. Strangely enough, this also worked like expected.

So my best guess is that the request body actually send differs from what is shown in the body hover popup. I don't know how I can solve the issue, as directly pasting the `identity_token` into the request body does not comply with the intended use case.

I pasted the contents of the request export below, with the sensitive information redacted.

### The HTTP request
```json
{"query":{"compType":"restApi","comp":{"bodyType":"application/json","body":"{\n  \"IdentityPoolId\": \"REDACTED\",\n  \"AccountId\": \"REDACTED\",\n  \"Logins\": {\n    \"cognito-idp.eu-central-1.amazonaws.com/REDACTED\": {{identity_token}}\n  }\n}","httpMethod":"POST","path":"https://cognito-identity.eu-central-1.amazonaws.com/","headers":[{"key":"Content-Type","value":"application/x-amz-json-1.1"},{"key":"X-Amz-Target","value":"AWSCognitoIdentityService.GetId"}],"params":[{"key":"","value":""}],"bodyFormData":[{"key":"","value":"","type":"text"}]},"id":"63e24639f9acee59e2c5a27f","name":"Get Identity Id","order":0,"datasourceId":"#QUICK_REST_API","triggerType":"manual","onEvent":[],"notification":{"showSuccess":true,"success":{"text":""},"showFail":true,"fail":[{"text":"","condition":""}],"duration":""},"timeout":"","confirmationModal":{"showConfirmationModal":false,"confirmationMessage":""},"periodic":false,"periodicTime":""},"inputs":[{"name":"identity_token","description":"","value":"REDACTED"}]}
```

**Comment by tewalts-mentech** [comment]
Have you tried turning it off and on again?

**Comment by neon-balcony** [comment]
Hey @Peterkrol12, thanks for the post. Could you please provide corresponding screenshots of the query configuration for all the working/not-working cases mentioned above?

**Comment by Peterkrol12** [comment]
Hi @neon-balcony 

Thanks for the quick reply!

### Not working 
![image](https://user-images.githubusercontent.com/42931791/217476986-2f67ccd4-434b-48cc-9461-945abd58d020.png)

### Working
![image](https://user-images.githubusercontent.com/42931791/217477198-6deb6f7d-fcb0-4333-9924-9937300e2e36.png)

The contents of the body hover popup pasted into Insomnia:
##### OpenBlocks
![image](https://user-images.githubusercontent.com/42931791/217477436-54fc38ab-b44a-4f1f-955a-d07c85d20bb1.png)

##### Insomnia
<img width="540" alt="image" src="https://user-images.githubusercontent.com/42931791/217477690-08d65d87-bc28-4807-946f-cbdc191073e4.png">

Let me know if I can assist any further!

**Comment by neon-balcony** [comment]
With some debugging effort, it seems that Amazon has got its specific JSON format `application/x-amz-json-1.1` and Openblocks failed to recognize that. I'll add a special case to handle it. Btw which version are you using now, cloud, self-hosted image or a self-compiled version?

**Comment by Peterkrol12** [comment]
Couldn't thank you enough for your efforts, greatly appreciated!

I am using the self hosted image version, [v1.1.4](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.4) to be specific

**Comment by neon-balcony** [comment]
Hey @Peterkrol12 , I submitted a [commit](https://github.com/openblocks-dev/openblocks/commit/72228ede922482b3ed333fd14f97055c6897b5cc) to solve this issue, please upgrade to the latest image and see if it works now.

**Comment by Peterkrol12** [comment]
Hi @neon-balcony, works like a charm!

Again, huge thanks for your efforts! I'll close the issue now :)
