### ISSUE TITLE
Collapsable Container suggestion: collapsed property

### ISSUE THREAD

**Issue by zuroma999** [openblocks-dev/openblocks#246]
Would be great if the collapsable containers had a 'collapsed' boolean property, so they could start off collapsed, or be controlled by code.

**Comment by Simonaaaa-C** [comment]
Hi, thanks for your feedback!

Currently You can use `{{collapsibleToggle1.value}}` to control the condition of collapsible container. See the figure below.
![image](https://user-images.githubusercontent.com/102499458/217704214-f430b4c5-c16e-425f-8f78-5166d566a9b6.png)

Can this meet your needs?

**Comment by zuroma999** [comment]
Great, thanks!
