### ISSUE TITLE
How to integrate an Openblocks app into a website or intranet?

### ISSUE THREAD

**Issue by bachi76** [openblocks-dev/openblocks#25]
I see a lot of potential for us as app developers to seamlessly integrate Openblocks apps into existing websites or intranets. Or even our own applications, that could intergate parts built with Openblocks. Sharing data between the page hosting the app and the app would be crucial. This is e.g. rather cumbersome when using iframes.

Is there an example how this works with Openblocks?

**Comment by hanshuai** [comment]
Embedding pages as native react components is the main feature of Openblocks.
Very glad to know you like it. It’s in the pre-alpha stage now and I think documents can be provided in a week.

**Comment by bachi76** [comment]
Cool, great to know! The ability to integrate low-code/no-code parts seamlessly with coded apps is a great advantage over all those other tools that concentrate on zero-developer environments. Helping actual devs and teams to build stuff faster without compromising on quality is what's still needed. Glad you're going to fill that niche!

**Comment by sarike** [comment]
@bachi76 hi, we have release a openblocks-sdk version to npm. 

https://www.npmjs.com/package/openblocks-sdk

And, you can find some demos here: https://openblocks-dev.github.io/openblocks-sdk-demo/#/basic-crud

Welcome to try it out and give us your suggestions.
