### ISSUE TITLE
Table on row select event doesn't fire when value of row changes

### ISSUE THREAD

**Issue by jmif** [openblocks-dev/openblocks#251]
If a table has row 1 selected and then an event causes the table to load different data, thus changing the value of row 1 (but not the selection) the row selection change event doesn't fire (but data sources linked to the selected row do update).

**Comment by lmx1117** [comment]
The row select change event is triggered when you have your selectedRow(s) changed, but when you reload your data, you are changing the content not the selectedRow(s)

**Comment by jmif** [comment]
That makes sense, maybe there is a different way to achieve the use case I'm looking at.

Here's a bit more detail: I have a table that has single row selection enabled.  I have queries that pull data based on the data in the selected row (ie `tab.selectedRow.data.id`).  I have a couple triggers that can cause the data in the table to change (ie press a button, causes data in the table to completely change).  When I do this, the queries are properly updated (ie the selected row data seems to change and thus the queries run again).  However, if I have an event tied to the "selected row change" that I then use to to calculate some data / run some other queries and I need that to run when the selected row changes and when the data in the row changes.  

I probably want a "data in table changed", which makes me think I can just hook into the event of the source query.  I think its easier to understand the event tree (something that be hard with these tools) if everything is based off the table but the event seems a bit convoluted.

I'll close this out and go with that approach but feel free to open if you'd like to chat more about it happy to provide input.

**Comment by neon-balcony** [comment]
Hey @jmif , we're about to publish a new feature named "data responder" so that you can observe its value change (`table1.selectedRow` for your case) and trigger subsequent actions, I'll keep you informed once it's released.

**Comment by neon-balcony** [comment]
@jmif Hey, please check out our new version for the "data responder" feature! Demo app: see [here](https://cloud.openblocks.dev/apps/63f84d23f5f6f66102fedf81/view)

**Comment by jmif** [comment]
Amazing thank you!
