### ISSUE TITLE
Date Range Validation Problem

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#257]
If you use the Date Range module and you want to validate it for example allow only 5 days, it is not working as expected.

I put in the Validation:

Min date -> {{dateRange1.start}}
Max date -> {{moment(dateRange1.start).add(5, "days")}}

After that when you try to select a range of days, it allows you to select more than 5 days.
After that if you only try to select again the range, it has computed the correct 5 days to only allow you to select.

This is not the expected behavior. 

I attach a screen record to see.

https://user-images.githubusercontent.com/68512501/218764007-b09b4a38-2cd4-41b8-83ed-c8da56cbeef4.mp4

**Comment by yuukaBlack** [comment]
Thank you for reporting this issue. We will fix that.

**Comment by YoJayz** [comment]
Hi @MichalisDBA, this issue has been fixed in Openblocks [v1.1.6](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.6). Please check it out!

**Comment by MichalisDBA** [comment]
@YoJayz Thanks, it is working now!
