### ISSUE TITLE
Empty value of Rich Text Editor

### ISSUE THREAD

**Issue by arivoallan** [openblocks-dev/openblocks#258]
Hi Team,
In the 'Rich Text Editor' component, the initial value is indeed `""`. 
But after editing and then deleting the content, we can no longer get an empty value, the empty value becomes `"<p><br></p>"` .
(this is annoying if we want to check the presence of content in the element).

**Comment by sarike** [comment]
@arivoallan Treating `"<p><br></p>"` also as an empty value can resolve your problem?

This is caused by the ReactQuill and quill.js that the 'Rich Text Editor' build on.

**Comment by arivoallan** [comment]
If it's always `"<p><br></p>"`, it's ok to treat this as empty value

**Comment by sarike** [comment]
@arivoallan Yeah, it's always.
