### ISSUE TITLE
Uploading files to specific folders using S3 datasources

### ISSUE THREAD

**Issue by meong1234** [openblocks-dev/openblocks#265]
Hi there!

I'm trying to upload files to a specific folder in S3 using datasources, but I'm having trouble with the file names getting URL encoded. Here's the format I'm using for the filename:

```
myfolder/{{input1.value}}
```

However, when the file is uploaded, the name is encoded as "/myfolder%2Fscan-file.png". Is there a way to prevent the URL encoding from happening? Or is there a different way to upload file to specific folder?

Any help or advice would be greatly appreciated. Thank you in advance!

**Comment by sarike** [comment]
@meong1234 Thanks for your reporting. This is bug. We'll fix this asap.

Are you using the cloud version or self-hosting version?

**Comment by meong1234** [comment]
@sarike self-hosting version
