### ISSUE TITLE
input autofocus

### ISSUE THREAD

**Issue by dueni0** [openblocks-dev/openblocks#268]
Is there an option to set autofocus for an input element?

**Comment by hanshuai** [comment]
Currently not, but I think this feature will be available soon

**Comment by neon-balcony** [comment]
Hey @dueni0 , `input` component provides a method `focus()` and you can use a JS query to trigger that (for this example below the `input2` will be set focused on page load), have a try 😃 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/118174126/220001832-7e020a77-17d6-4edd-9f4a-10771a022a58.png">

**Comment by dueni0** [comment]
works perfect, thank you @neon-balcony
