### ISSUE TITLE
REST API query doesn't run on page load

### ISSUE THREAD

**Issue by nemulos** [openblocks-dev/openblocks#27]
I have configured a REST API query to fetch data from an API server, and using the control component event handler to write response from API server to a text output component. However, the REST API query doesn't get triggered on page load.

<img width="2076" alt="on-page-load-issue-openblocks" src="https://user-images.githubusercontent.com/96138322/202278817-7fe33c9f-7911-4da0-840b-8c17e5601a65.png">

Invoking the query via a button works.

**Comment by sarike** [comment]
I can reproduce this bug. This occurs when the query references itself. We'll dig into it and fix soon.

Now, you can delete the query's success event handler and set `{{query1.data}}` in text1's value field.

**Comment by sarike** [comment]
@nemulos this issue is fixed and cloud version updated.
