### ISSUE TITLE
Is openblocks production ready?

### ISSUE THREAD

**Issue by r3nor** [openblocks-dev/openblocks#28]
I want to use OpenBlocks as an internal tool for my company. We are currently using AppSmith, but I find openblocks more pleasant and fun to use. My questions are:

- Is openblocks stable?
- Is openblocks production ready?

Thank you for such an awesome tool!

**Comment by hanshuai** [comment]
Yes, Openblocks is stable and production-ready. We've spent a lot of time on type safety and unit tests to ensure the stability of the platform.
The next most important updates we'll be making are more data-source/API integrations and documents.

**Comment by r3nor** [comment]
Thank you.
