### ISSUE TITLE
I really want to know the cause and team of openblocks

### ISSUE THREAD

**Issue by evanlabs** [openblocks-dev/openblocks#281]
I really want to know the cause and team of openblocks

I really like this low-code platform, I think openblocks is closer to what I want than low-code platforms such as appsmith or budibase.

At the same time, I am also curious about what team created openblocks for what reason.

It's amazing.

Can someone answer these mysteries?

**Comment by hanshuai** [comment]
Hi, I’m Steven Han, co-founder of Openblocks. So glad that you like it!
I was an ex-Googler on the knowledge graph team and tech lead of a short video platform named Kwai. Openblocks is backed by a small remote team that raised seed funding from IDG CAPITAL. This information will be on the official website soon.
In the “Why Openblocks” section of the README.md page, it’s the mission and philosophy:
> An all-in-one IDE to create internal or customer-facing apps.
> A place to create, build and share building blocks of web applications.
> A domain-specific language that UI-configurable block is the first-class citizen.

And here is the [roadmap](https://github.com/orgs/openblocks-dev/projects/1).
I hope that answers your question.😀

**Comment by evanlabs** [comment]
Openblocks is so cool.

Is there a commercial version besides the open source community version?
Where can I get more information?

Can I chat with you via WeChat?

**Comment by hanshuai** [comment]
There is a commercial version, but it's not publicly available yet.
For more information, you can chat with us on https://discord.com/invite/z5W2YHXdtt
