### ISSUE TITLE
[Bug] Little bug with the OpenAI API

### ISSUE THREAD

**Issue by LibertyPrimer** [openblocks-dev/openblocks#286]
Hello, congratulations for the hard work developing this, I'm using it for my Non-Profit and is helping us a lot!

I was testing the OpenAI integration you have, and the generation of images work so fine, but the modification of images give me error due to the image I send via API to OpenAI don't achieve the requeriments.

```
{
  "error": {
    "code": null,
    "message": "Uploaded image must be a PNG and less than 4 MB.",
    "param": null,
    "type": "invalid_request_error"
  }
}
```

I check and is a 40KB square png image, i found in some forums that this is because the API have a problem with the type of the png file generated by Typescript when is casted.

As i found, it suppose to can be solved adding "as Any" in the casting.

I don't really know if this is the solution because I'm not experimented enough to text directly, but hope this little investigation helps.

**References:**
[OpenAI Forum](https://community.openai.com/t/using-image-url-in-images-edits-request/27247/13?page=2#:~:text=Jan%202-,OK%2C%20so%20casting%20may%20be%20part%20of%20your%20problem.,Any%20when%20you%20pass%20images.%20It%20is%20a%20Typescript%20specific%20issue.,-Here%20are%20two)

**Comment by sarike** [comment]
@LibertyPrimer 

Could you toke a screenshot of your query settings to me?

Try config the file field in this way:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/1788906/221826120-1630436f-f03c-42dd-a3d5-d4fd62f2c37b.png">

**Comment by LibertyPrimer** [comment]
I had this one before:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/43355491/221833039-7fdfe2f2-dc46-46f5-83f3-175430cd7128.png">



I tried the field field you send me but still give me the same problem

<img width="796" alt="image" src="https://user-images.githubusercontent.com/43355491/221833295-92f60653-aa78-42d6-873d-0ddb1063cd12.png">

**Comment by sarike** [comment]
@LibertyPrimer 

I just checked the source code, the cause of this issue is the empty value of the `mask` field. For empty file field, we mistakenly passed an illegal file to OpenAI.

The workaround now is setting a mask image too.

We'll fix this issue asap.
