### ISSUE TITLE
query request time out

### ISSUE THREAD

**Issue by KingMin-jpg** [openblocks-dev/openblocks#288]
I want to know, does the request forwarding gateway of openblocks query have a request timeout limit of 60 seconds?
![d7291283508cf5330933d7bdfdf475f](https://user-images.githubusercontent.com/55698932/222369667-abd3f9c0-efbb-452c-b575-9bd3c2697972.png)

**Comment by lmx1117** [comment]
> I want to know, does the request forwarding gateway of openblocks query have a request timeout limit of 60 seconds? ![d7291283508cf5330933d7bdfdf475f](https://user-images.githubusercontent.com/55698932/222369667-abd3f9c0-efbb-452c-b575-9bd3c2697972.png)

Hi @KingMin-jpg , thank you for raising this, yes we have a 60 second timeout limit for requests, and 120 seconds max, you can actually check it out here, and we will update the Default value asap, sorry to bother you.
![image](https://user-images.githubusercontent.com/116335720/222615839-71702ab3-7cbe-4b59-bb13-35d3ae618a5b.png)

**Comment by lmx1117** [comment]
@KingMin-jpg Please update your image, we have fixed it now. Thanks again for your patience.

**Comment by KingMin-jpg** [comment]
> @KingMin-jpg Please update your image, we have fixed it now. Thanks again for your patience.

No, this seems to be a gateway problem on your side, your gateway may have set a maximum of 60 seconds for the request response link, how do I update my image, because my side still hasn't changed, it's still timeout, and I set 120s in "Timeout after" here
![image](https://user-images.githubusercontent.com/55698932/222694740-4fd3d01b-5616-47ed-b902-5c6cb71ba427.png)

**Comment by lmx1117** [comment]
Wait, are you using the cloud environment or self-host?

**Comment by jerry-goodman** [comment]
Hi @KingMin-jpg. This is because our nginx has a default timeout of 60 seconds, which caused the issue. Currently, we have updated both the cloud environment and the self-host image to fix this problem.

**Comment by KingMin-jpg** [comment]
> Hi @KingMin-jpg. This is because our nginx has a default timeout of 60 seconds, which caused the issue. Currently, we have updated both the cloud environment and the self-host image to fix this problem.



> Wait, are you using the cloud environment or self-host?

Good evening, yes, it has been solved now, thank you very much. Please understand that my grammar is not good.

**Comment by Pratyush1197** [comment]
@lmx1117 this issue is still occurring for me.
