### ISSUE TITLE
Can't use array value in default value

### ISSUE THREAD

**Issue by r3nor** [openblocks-dev/openblocks#29]
I am using a cascader select and writing its value on an SQL backend. It gets written to a varchar variable, and it writes the whole array to the variable.

Then I am unable to use the saved array as a default value for the cascader and I think this is because of escaping characters:

![](https://i.imgur.com/4IT2RF1.png)

```
TypeError: Type "Array" is required, but find value: "[\"magento\",\"magento-6\"]"
```

**Comment by sarike** [comment]
@r3nor try `{{JSON.parse(projectsTable.selectedRow.tech)}}`

**Comment by neon-balcony** [comment]
Hi @r3nor ,
I think the error message is pretty straightforward, value `"[\"magento\",\"magento-6\"]"` is a stringified string value where the wanted type here is Array<String>, so you should call `{{ JSON.parse(...) }}` as described by @sarike.

**Comment by r3nor** [comment]
Solved. Thank you.
