### ISSUE TITLE
Navigation icons too close to text

### ISSUE THREAD

**Issue by r3nor** [openblocks-dev/openblocks#30]
![](https://i.imgur.com/I5ZIBjh.png)

When creating a navigation, the icons appear too close to the text, and it is somewhat unpleasant to the eye.

**Comment by hanshuai** [comment]
Thanks for your feedback, we'll fix it in the next version.

**Comment by neon-balcony** [comment]
Hi @r3nor, 

This issue has been fixed in our latest version, thanks for the feedback!
