### ISSUE TITLE
Correct way to display array of strings as HTML list

### ISSUE THREAD

**Issue by agolosnichenko** [openblocks-dev/openblocks#301]
Hi! I need your advice on following:
1. I have an array of strings comming from my API backend
2. I want to display that data as HTML or Markdown list using the Text Widget

What is the correct way to do that? I've tried to use Array.map function, but seems that it adds some weird commas in the output
<img width="1439" alt="Screenshot at Mar 09 21-33-33" src="https://user-images.githubusercontent.com/60524281/224073622-1e68dcc1-9d15-4ad3-82c0-f88452f4be2d.png">

**Comment by agolosnichenko** [comment]
So, as workaround I've removed these weird commas with String.replaceAll function, but I hope that there is easier way to do that :-)
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/60524281/224076784-caa70726-9910-45b3-911f-d7278bf26e19.png">

**Comment by ggbond2077** [comment]
> Hi! I need your advice on following:
> 
> 1. I have an array of strings comming from my API backend
> 2. I want to display that data as HTML or Markdown list using the Text Widget
> 
> What is the correct way to do that? I've tried to use Array.map function, but seems that it adds some weird commas in the output <img alt="Screenshot at Mar 09 21-33-33" width="1439" src="https://user-images.githubusercontent.com/60524281/224073622-1e68dcc1-9d15-4ad3-82c0-f88452f4be2d.png">


The text widget requires a string value. Since the map function returns an array and auto toString() is applied, some commas will be added. To fix this, you can join the array elements into a string:
```html
<ul>
{{
["a", "b", "c", "d"].map((_, idx) => `<li>${idx}</li>`).join("")
}}
</ul>
```
