### ISSUE TITLE
wrong margin when disable toolbar in inner table on expandable table

### ISSUE THREAD

**Issue by smkthat** [openblocks-dev/openblocks#303]
![alt text](https://i.postimg.cc/x8ZySVZm/2023-03-11-01-57-47.png "margin issue")
![alt text](https://i.postimg.cc/VLR0M8gW/2023-03-11-020340701.png "margin issue")
to fix this:
`.ant-table.ant-table-middle .ant-table-tbody .ant-table-wrapper:only-child .ant-table {
    margin: -2px -8px 0px 0px;
}`

**Comment by lmx1117** [comment]
Thanks for reporting this, checking now🫡

**Comment by YoJayz** [comment]
Hi @smkthat , this issue has been fixed in our latest release. Please check [v1.1.8](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.8) now, and thanks again for reporting this issue!
