### ISSUE TITLE
Confirmation Copy Text Style (Bug?)

### ISSUE THREAD

**Issue by TomKremer** [openblocks-dev/openblocks#307]
Hi,

I noticed that my system cannot display the font used on confirmation dialog box, see attachment.
![Screenshot 2023-03-12 at 09 22 29](https://user-images.githubusercontent.com/1757397/224532991-f2469fd5-cf15-4f7f-8bbc-1710dddf67f8.png)

When I disable the font-family (PingFangSC-Regular) on the copy block it works fine.
![Screenshot 2023-03-12 at 09 23 58](https://user-images.githubusercontent.com/1757397/224533067-1912f1a4-5e81-493f-b78f-789d50599540.png)

I don't know if that font is used elsewhere but could it be a bug?

Best,
Tom

**Comment by lmx1117** [comment]
Hi Tom, in fact, the font of the confirmation modal is not supported to be modified 🥲, and modifications like this are temporary.

**Comment by lmx1117** [comment]
Hi Tom, thanks for reporting this, we will fix it asap.

**Comment by lmx1117** [comment]
@TomKremer Tom, this issue has already been fixed, please update OB and check it out, thanks again for your patience.❤️

**Comment by TomKremer** [comment]
Thanks for the quick update! It works.
