### ISSUE TITLE
Performance issue with List View - help

### ISSUE THREAD

**Issue by SvV-CWinJS** [openblocks-dev/openblocks#311]
Coding in Openblocks works like a breeze.

I'm building a sort of ticketing system with it. The most complex page (until now) can be seen on the screenshot below.

The list of past notes on the ticket can be seen on the lower left (List View). The data from that view comes from a temporary state.
Users can edit and delete past notes. They can also see attachments added to that note via the dropdown (which will open a object URL in a new page derived from base64 data).

After clicking the edit button, it takes a second or 2 before the note becomes editable (i.e. the Rich Text View becomes no longer read-only and the toolbar appears).
After changing the selection from the attachment, it takes up to 4 seconds before the attachment is opened in a new page (more precise: before the Javascript of the onchange runs).

I've extracted the list view in question and made a separate app from it, for testing purposes. See my attached JSON for this app.
Unfortunately, the lag with opening the attachment is not present in this extracted List View. Note: only the attachment of the first note in the list contains usable data.

Is there any way I can increase the responsiveness of performance of this list view? Is their perhaps a way to increase performance on Openblocks side?

Thank you in advance for any help.

![image](https://user-images.githubusercontent.com/20355847/224923122-73289e2b-6bfb-4f2d-86da-eb8fd6a89b6e.png)
[test List View performance.json.txt](https://github.com/openblocks-dev/openblocks/files/10965209/test.List.View.performance.json.txt)

**Comment by lmx1117** [comment]
@SvV-CWinJS What a cool app! Very impressive! We are checking the performance issue, and it’s very nice of you to provide the test app JSON ❤️

**Comment by SvV-CWinJS** [comment]
Thanks for the compliments.

It seems I had mist something when copying and pasting when creating the test app.
The lag with opening the attachment can be reproduced when the source data of the list view has a million characters (several base64 URLs).

**Comment by SvV-CWinJS** [comment]
Since it is difficult to replicate the exact performance issue on a seperate case, I exported the entire app to a JSON (including data).

Please only consider the large list view on the left.

I would like to ask someone with insight to take a look at these performance issues (from highest to lowest performance):

1. When I move my mouse pointer over the pencil and trash can icons of the view, there is a slight delay in the highlighting of the icons (the blue background that appears on hovering).
2. Pressing a pencil, makes the corresponding Rich Text Field (left of the pencil) editable. With my browser, it takes a second or 2 before the field is editable.
3. Please open the first dropdown that occurs in the list, next to "Bijlagen:", and select "20230216 LLB DEMA-SHOP N.V..html". With my browser, it takes **_14 seconds_** before an information message pops up stating "The base64 starts with: ..." (which is the result of the Javascript code I programmed behind the Change event).

Please note that for point 3, only the very first dropdown contains "relevant" data.

Can someone tell me why there is such a long lag and how I can improve this?
[test performance list view (second).json.txt](https://github.com/openblocks-dev/openblocks/files/11016160/test.performance.list.view.second.json.txt)

**Comment by SvV-CWinJS** [comment]
I humbly must admit that the third point is my own mistake.
I misinterpreted "debounce", and put "15s" there. When removing the "15s", the Javascript code runs instantly.

Only point 2 remains relevant, but the delay is acceptable, so I'm closing this issue.

**Comment by lmx1117** [comment]
> I humbly must admit that the third point is my own mistake. I misinterpreted "debounce", and put "15s" there. When removing the "15s", the Javascript code runs instantly.
> 
> Only point 2 remains relevant, but the delay is acceptable, so I'm closing this issue.

Haha, well, we still need to improve the 1, 2 you mentioned, and if it is convenient, I would also like to ask how you feel when using OB, suggestions are always welcome! (Again, awesome app, worth learning 👍
