### ISSUE TITLE
[Suggestion] Make query list more maintainable

### ISSUE THREAD

**Issue by SvV-CWinJS** [openblocks-dev/openblocks#312]
Hi

I would like to suggest to implement a method of ordering or sorting of the query list in the below window (screenshot).
![image](https://user-images.githubusercontent.com/20355847/224930533-5b43ad85-7040-432b-86c2-533a7208b4ed.png)

Perhaps you can:

- Let the user sort the list
- Make the items draggable so they can sort them themselves
- Make it possible to add them in folders
- Make it possible to search for a query name

**Comment by lmx1117** [comment]
Nice suggestions. We will find out how to make it more convenient for users

**Comment by hialvaro** [comment]
This would be awesome

**Comment by YoJayz** [comment]
Hi all, we've supported search function and folder management for query list in the query editor. Please check [v1.1.8](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.8) now! 
Also, we'll continue improving on this to make it more capable. Thanks for your advice!
