### ISSUE TITLE
Table Sort Issue

### ISSUE THREAD

**Issue by TomKremer** [openblocks-dev/openblocks#313]
Hi,

I have a table with artists sorted by artist name asc but the order is incorrect.

Example:
"" > Empty names first: ok
"ATELIER" > A, first: ok
"Board Design" > B, second, ok
"Huddle" > ok
"arnold" > **not ok**
"leonardo" > **not ok**

Do I need to configure the cell differently or is this a bug?

Best,
Tom

**Comment by lmx1117** [comment]
Hi Tom, sorry for the late reply, it's a bug and we will fix it asap, thanks for reporting this🫶

**Comment by YoJayz** [comment]
Hi @TomKremer , this bug has been fixed in our latest release. Please check [v1.1.8](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.8) now! Thanks again for reporting this!
