### ISSUE TITLE
Modal module missing inside Canvas

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#32]
If you drag and drop a Modal module inside canvas work area then to find it again you have to look at the left sidebar Components section.

It is missing or it does not have any indication that it exists inside canvas work area.

![image](https://user-images.githubusercontent.com/68512501/202398377-39729e02-11db-4958-b542-4a361799d90f.png)

It would be great to see where the Modals modules are inside the canvas work area.

**Comment by agaitan026** [comment]
👍

**Comment by lmx1117** [comment]
Hi MichalisDBA, this issue is already solved, please check it out, and thanks again for your advice and patience. 😉
