### ISSUE TITLE
Public Key Retrieval is not allowed.

### ISSUE THREAD

**Issue by CrispCrew** [openblocks-dev/openblocks#320]
Using MySQL as a Data Source produces this error during ANY query.

https://cdn.discordapp.com/attachments/1040509691433857036/1086071720009551932/image.png

**Comment by CrispCrew** [comment]
Edit: Fixed using SSL and SHA256 Auth

**Comment by JulesThuillier** [comment]
How does that solves the problem ?
The [MySqlConnector.java](https://github.com/openblocks-dev/openblocks/blob/develop/server/api-service/openblocks-plugins/mysqlPlugin/src/main/java/com/openblocks/plugin/mysql/MysqlConnector.java) should actually add the following config to make it work properly with non SSL connections : "allowPublicKeyRetrieval : true".
