### ISSUE TITLE
Iterate through an array and query each item

### ISSUE THREAD

**Issue by twhug** [openblocks-dev/openblocks#322]
I'm not sure if this is a duplication of #283 because of the wording, it's a bit ambiguous.

I have an array of items selected in a 'TreeData' field. For each selected item, I want to run a further query (i.e. to get more information about the selected items, but not the unselected ones).

It's easy enough to iterate through the selected items. I also have a **temporary state**, to try and keep track of the current iteration. 

My query references the value of the **temporary state** but each time the loop runs, it uses the same 1 item from the 'selected' array. So if I have 4 items selected, the further query instead returns the same set of results, 4 times.

I have tried using various async functions etc. rather than just standard looping constructs but this doesn't make any difference.

Looking at something like Retool - it seems they solve this issue by allowing you to essentially supply an argument to a query, in-code. They seem to call it [an 'additionalScope'](https://community.retool.com/t/how-to-run-a-rest-api-query-for-each-item-in-an-array-and-return-all-results-together/2352) - would we potentially be able to get support for something similar? Or is there a workaround already available that I could leverage to achieve this type of functionality?

**Comment by neon-balcony** [comment]
Hey actually we do support passing in parameters, check out this [doc](https://docs.openblocks.dev/build-apps/write-javascript/javascript-query#pass-in-parameters)

**Comment by twhug** [comment]
Dang, not sure how I wasn't able to find that in the doc, I was looking for that specifically.

It does appear to have solved my problem, so this can be closed 👍 thanks for the good advice.
