### ISSUE TITLE
How to escape curly bracket?

### ISSUE THREAD

**Issue by meowcat** [openblocks-dev/openblocks#33]
I cannot find in the documentation how I would go about escaping a single curly bracket.

Usecase: Django Dynamic REST filter string https://github.com/AltSchool/dynamic-rest#filtering

For example, I have `cpds_table.filter.filters[0]= '{'columnKey': 'mass', 'operator': 'gt', 'filterValue': 300}` . 

My query should be `http://myendpoint?filter{mass.gt}=300`
`filter{{{cpds_table.filter.filters[0].columnKey}}.{{cpds_table.filter.filters[0].operator}}}` doesn't work.
I tried: `\{, '{', "{", {{{}}` but I'm running out of ideas :)

**Comment by meowcat** [comment]
Very verbose workaround: define a transformer `cb`: `return '{'`, then use `{{cb.value}}` for a single curly bracket

**Comment by neon-balcony** [comment]
Hi thanks for the report, we're currently investigating on escaping special characters.

For now, I think you can use string concatenation with curly brackets as a work around:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/118174126/202451867-0f79b280-72bf-4731-a070-22ade0a9112f.png">
