### ISSUE TITLE
[urgent] Add License to openblocks-dev-utils

### ISSUE THREAD

**Issue by onkee** [openblocks-dev/openblocks#334]
We are attempting to self-host Openblocks. However, because we are behind a proxy, without proper licensing attributions we cannot install all of the necessary packaging. We have found that openblocks-dev-utils is missing licensing in the package.json. Can this please be added?

**Comment by sarike** [comment]
Your PR merged. Thanks. We'll check other packages as well.

**Comment by onkee** [comment]
@sarike - Thank you very much! Do you happen to know when a new version will be released to NPM so that I can pull in the changes?
