### ISSUE TITLE
Links column in table not using full column width

### ISSUE THREAD

**Issue by zuroma999** [openblocks-dev/openblocks#338]
Not sure if this is a bug. If it's not a bug, it would be great if this behavior was fixed.

Right now, no matter how wide a table column for Links is made, it only shows 3 items, then an ellipses. Would be nice for it to fill the usable space in the column.

<img width="483" alt="Screenshot 2023-03-23 at 2 09 23 PM" src="https://user-images.githubusercontent.com/49953523/227362627-a814068a-c67a-469f-9c2d-654bc3c6ccfb.png">

**Comment by ggbond2077** [comment]
Sorry for the confusion, this is by design. We will optimize it in the next version.

**Comment by ggbond2077** [comment]
> Not sure if this is a bug. If it's not a bug, it would be great if this behavior was fixed.
> 
> Right now, no matter how wide a table column for Links is made, it only shows 3 items, then an ellipses. Would be nice for it to fill the usable space in the column.
> 
> <img alt="Screenshot 2023-03-23 at 2 09 23 PM" width="483" src="https://user-images.githubusercontent.com/49953523/227362627-a814068a-c67a-469f-9c2d-654bc3c6ccfb.png">

We just released a hotfix, you can try updating it.

**Comment by zuroma999** [comment]
Thanks so much!
