### ISSUE TITLE
openblocks-sdk does not work with nextjs

### ISSUE THREAD

**Issue by mingfang** [openblocks-dev/openblocks#344]
openblocks-sdk does not work with nextjs.
Getting this error
```
error - ReferenceError: window is not defined
    at file:///home/projector-user/IdeaProjects/next-openblocks-test/node_modules/openblocks-sdk/dist/36af6c29.js:2239:53
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  page: '/'
}
```

I create this repo to demonstrate the problem.
https://github.com/mingfang/next-openblocks-test

**Comment by sarike** [comment]
@mingfang Thanks for reporting this, I will release a new version of SDK soon.

But it can only be used as dynamic import as well.

**Comment by sarike** [comment]
@mingfang Try `openblocks-sdk@0.0.40`.

**Comment by mingfang** [comment]
@sarike 
I can confirm that dynamic import works now. Thanks.
Please push the code.

Also are there plans to make the sdk work without dynamic import?

**Comment by mingfang** [comment]
@sarike 
I can confirm that dynamic import works now. Thanks.
Please push the code.

Also are there plans to make the sdk work without dynamic import?

**Comment by mingfang** [comment]
@sarike 
I can confirm that dynamic import works now. Thanks.
Please push the code.

Also are there plans to make the sdk work without dynamic import?

**Comment by mingfang** [comment]
I just noticed the styles are not the same when running the demo app using the SDK vs directly in OB.
I'm guessing the css are not scoped completely.
