### ISSUE TITLE
How to retrieve the user ID of the currently logged-in user?

### ISSUE THREAD

**Issue by biankasyo** [openblocks-dev/openblocks#380]
I have a management system where users can update information. However, I need to record the user who created or updated the information. I want to ask how to retrieve the user ID of the currently logged-in user.

I've checked the wiki, but I couldn't find any relevant information on how to implement this. Can anyone help me with this issue?

Thank you!

**Comment by mingfang** [comment]
`{{currentUser.id}}`

**Comment by biankasyo** [comment]
> `{{currentUser.id}}`

Thank you!
