### ISSUE TITLE
Control component Action doesn't list any components

### ISSUE THREAD

**Issue by alzambo** [openblocks-dev/openblocks#39]
Hi,
trying to set a component action, if I choose the "Control component", I cannot find any component to bind to.
See attached screenshot:
![image](https://user-images.githubusercontent.com/10614142/202659875-b0b1c649-da71-4203-9338-0b7757b917b9.png)

Alex

**Comment by lmx1117** [comment]
You need to drag the component you want into the canvas for control. For example, there are only a table  component and a select component on the canvas now, when you set event handlers for select, you can only control the table, but we generally cannot control the events of the table component, so drag other components for a try.

**Comment by alzambo** [comment]
Ok, thank you...
