### ISSUE TITLE
Enhancements to Table: runtime configuration, additional state info

### ISSUE THREAD

**Issue by meowcat** [openblocks-dev/openblocks#41]
https://gist.github.com/meowcat/12e22150f8abf8fc364f951b236e46bc

I am working on a "CSV editor" module. Right now this works with a WebDAV enabled server.
* Module input is server and path
* GET/PUT reads/writes the CSV from server, Papa Parse goes CSV<->JSON
* (Right now there is no login etc and only intended for local use)

* A Table view displays the table
* An "Edit" column opens a JSON Schema form modal
* the JSON Schema is generated from the currently selected row

The only thing missing is: I cannot update the columns if the users' format changes. I would need to: 
* either have a way to trigger "regenerate columns" with code
* or a way to set columns directly.

**Comment by meowcat** [comment]
It would also massively simplify things if we had 
```table1.selectedRowIndex``` (or ```table1.selectedRowsIndex``` for multirow)

**Comment by lmx1117** [comment]
Hi meowcat, now you can dynamically set table columns, please check it out, and thanks again for your advice and patience. 😉

**Comment by meowcat** [comment]
It seems to be working!
I don't fully understand the behavior yet. As I see it:
* the columns *shown* are the intersection of defined columns (columns in the data + manually added columns), and columns in the "Column Setting" array?
* the order of columns is the order of first addition to the table? Could we show them in order of Column Setting array instead?

**Comment by ggbond2077** [comment]
> 
1. You're right, When "dynamic column setting" is turned on:
   a. Column Setting array is empty,  columns in the data + manually added columns are shown.
   b. Column Setting array is not empty, only the columns in the setting array are shown.

2. it should be shown in order of Column Setting array, we will fix that in the next release.

**Comment by lmx1117** [comment]
Hi meowcat, now we have fixed the issue of table column orders are not inconsistent with dynamic column setting, please check it out😎

**Comment by meowcat** [comment]
Thanks!
