### ISSUE TITLE
Add an option to prettify code in the code editors

### ISSUE THREAD

**Issue by gchartier** [openblocks-dev/openblocks#44]
I think it would be a really nice feature to add a "Format" or "Prettify" button under any JavaScript code editor or any code editor within Open Blocks UI.

**Comment by Simonaaaa-C** [comment]
Thanks for your suggestion!

Currently the keyboard shortcut **command + L**(Mac)/**control + L**(Wins) is supported to re-format in the code editor, and you could check more keyboard shortcuts in the bottom left corner. 
![image](https://user-images.githubusercontent.com/102499458/202830731-b1ea5c1b-d2ae-4a77-b00e-249816a965ab.png)

I hope this helps! Please let me know if I can help with anything else. 🫶
