### ISSUE TITLE
Publish a page for a public users?

### ISSUE THREAD

**Issue by leoborlot** [openblocks-dev/openblocks#45]
hy guys. 

Theres any way to publish an application for a public (nom logged people)?

This feature was very good in bubble. With this may we create tools for company leads and clientes send or check theyer information from our database.

**Comment by Simonaaaa-C** [comment]
Hi there!
To make an app public, you could click **Share** in the top right corner, toggle on the public setting and then share the app link to anyone.
![image](https://user-images.githubusercontent.com/102499458/202830288-fb730a9d-ff29-4744-bf49-356c82067cfa.png)
I hope this helps. Let me know if this does not solve your problem. 🫶

For more information about permission, please see our documentation. https://docs.openblocks.dev/workspace-management/permissions-for-resources

**Comment by leoborlot** [comment]
Yes, I found!! Thanks.
Theres any way to custom the url route?

**Comment by ggbond2077** [comment]
> Yes, I found!! Thanks. Theres any way to custom the url route?

See: https://github.com/openblocks-dev/openblocks/issues/31. Already in roadmap.

**Comment by agaitan026** [comment]
👍
