### ISSUE TITLE
UX: Expanded Code Editing Window Should Have Clearer Focus

### ISSUE THREAD

**Issue by gchartier** [openblocks-dev/openblocks#46]
When expanding (or folding/unfolding) the code editor, it's hard to tell when it's open or not because the expanded editor blends in with the rest of the UI.

There are several ways to address it but the one I think would offer the best UX is to blur the background when the code editor is expanded. When people are writing code they generally have their full attention on what they're writing and wouldn't care so much about the rest of the UI.

**Comment by neon-balcony** [comment]
Hi @gchartier,

Thanks for the post, I'm wondering there could be cases where you want to check the real-time UI updates while you're writing code (see record below), in that case using a blur might cause repeatedly folding and unfolding operations. It's a weigh of pros and cons IMHO.
![code-editor](https://user-images.githubusercontent.com/118174126/202889158-2b9603d0-f419-421d-801d-0eb4d6814b82.gif)

**Comment by neon-balcony** [comment]
Closed since no new comments have been added.
