### ISSUE TITLE
Setting temporary state docs doesn't link anywhere

### ISSUE THREAD

**Issue by sujeetpillai** [openblocks-dev/openblocks#47]
The documentation for setting temporary state in the event handlers documentation doesn't seem to link anywhere. Is that feature not ready yet?

**Comment by lmx1117** [comment]
sorry, we've been working on the docs now, we'll pick up our pace💪

**Comment by neon-balcony** [comment]
Hi @sujeetpillai,

Thanks for the report, temporary state function is well working now, but the documentation is still in progress. We'll add that soon.

**Comment by agaitan026** [comment]
👍

**Comment by sujeetpillai** [comment]
@lmx1117 Thanks. Love your tool btw.

**Comment by neon-balcony** [comment]
Hi @sujeetpillai, 

Thanks for the report, the documentation for [temporary state](https://docs.openblocks.dev/build-apps/write-javascript/temporary-state) has been added. Check it out!
