### ISSUE TITLE
Query Google Sheets

### ISSUE THREAD

**Issue by TychoCeltCast** [openblocks-dev/openblocks#49]
Hi!

If I see it correctly you can only Read the entire Google Sheet and not do a search query on it.
Goes fine for small sheets but if you have to retrieve 100.000s of lines, that will slow down the system :)

Would like to see a way such as SQL to do searches based on column, max results etc

**Comment by neon-balcony** [comment]
Hi @TychoCeltCast,

Thanks for the post, but I was wondering if Google has provided with search APIs? Please help submit it to us if you find one.
And to be honest, we previously thought Google Sheets is just for storing hundred of rows of data (maybe thousands), but never to the magnitude above 100 thousands where a real database (Postgres, MongoDB etc.) should be used considering performance and stability.

**Comment by TychoCeltCast** [comment]
Thank you @neon-balcony 
It does indeed seem that it does not exist in API directly.
A way around it that I've thought of would be to create a new tab,
use the =QUERY(A1:D234,"SELECT B, D" there, and then return the fields from that tab.

**Comment by neon-balcony** [comment]
Got it, does existing API support this operation? 
```
=QUERY(A1:D234,"SELECT B, D"
```

**Comment by TychoWerner** [comment]
> Got it, does existing API support this operation?
> 
> ```
> =QUERY(A1:D234,"SELECT B, D"
> ```

I don't think there is a API directly for it, I was thinking it could update a cell and this formula into it.
Wait for the results and get them :)

**Comment by TychoCeltCast** [comment]
It does work to change 1 row except it adds a `'`  to make it a string and not a formula 
<img width="429" alt="Scherm­afbeelding 2022-11-20 om 09 34 53" src="https://user-images.githubusercontent.com/107351632/202892968-e82929c6-5cae-4151-8045-9c9c30a540e9.png">

<img width="380" alt="Scherm­afbeelding 2022-11-20 om 09 34 46" src="https://user-images.githubusercontent.com/107351632/202892970-3b5ce5e9-06bb-48e5-a792-d7884fedf14e.png">

<img width="459" alt="Scherm­afbeelding 2022-11-20 om 09 34 43" src="https://user-images.githubusercontent.com/107351632/202892971-d36ab121-9542-47e4-bcba-2abdf8f9ffd2.png">

<img width="860" alt="Scherm­afbeelding 2022-11-20 om 09 34 40" src="https://user-images.githubusercontent.com/107351632/202892972-921d7a6a-7f7a-465e-a642-bc2d1bf19ad2.png">

<img width="879" alt="Scherm­afbeelding 2022-11-20 om 09 34 34" src="https://user-images.githubusercontent.com/107351632/202892973-9aec64ea-c739-4a9f-8c2f-4df8e6a4b55a.png">

<img width="409" alt="Scherm­afbeelding 2022-11-20 om 09 34 30" src="https://user-images.githubusercontent.com/107351632/202892974-78c503cc-dcc2-45bc-83cd-07d9a154b492.png">

<img width="380" alt="Scherm­afbeelding 2022-11-20 om 09 34 27" src="https://user-images.githubusercontent.com/107351632/202892975-0aad40ca-6465-4111-8a5e-c3185806b066.png">

**Comment by TychoWerner** [comment]
Any updates for this issue?

**Comment by neon-balcony** [comment]
Hi, does @TychoWerner's post above answers your question?

I believe what you want is Google's [query function](https://docs.google.com/document/d/1BV94ZVI1b1AkM0xOx503mfo01Yj9CVtdFXdQZzelGNk/edit#), but by skimming through the sheets [API docs](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGetByDataFilter), I don't think Google provides us with that accessibility.

**Comment by TychoWerner** [comment]
> Hi, does @TychoWerner's post above answers your question?
> 
> I believe what you want is Google's [query function](https://docs.google.com/document/d/1BV94ZVI1b1AkM0xOx503mfo01Yj9CVtdFXdQZzelGNk/edit#), but by skimming through the sheets [API docs](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGetByDataFilter), I don't think Google provides us with that accessibility.

Hi, that is actually also my account, accidentally switched.

My solution could work except that it adds a ' to the formula rendering it as a string

If there is a way to set a formula from OpenBlocks to Google Sheets I could continue on a solution.

**Comment by neon-balcony** [comment]
Okay, could you please record a short video to reproduce the issue about getting that  quote ' for your workaround? I kind of got lost by looking at the snapshots above.

**Comment by TychoWerner** [comment]
> Okay, could you please record a short video to reproduce the issue about getting that quote ' for your workaround? I kind of got lost by looking at the snapshots above.

Ofcourse! https://youtu.be/g4mrGJ7l_fs
Hope this helps 😃

**Comment by neon-balcony** [comment]
Thanks very much, now the issue is clear, we'll dig into that.

**Comment by TychoWerner** [comment]
This might be of assistance:
https://developers.google.com/sheets/api/samples/data#repeating_a_formula_over_a_range

It shows how a formula can be added

**Comment by lvhuichao** [comment]
After our debugging, we are sorry to find that the ' is automatically added by the google server to escape the formula as a string. And sadly we can't find a way to work around it as a formula.
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/33057362/205241251-46abb58c-8962-4914-8c8b-0619bbf91997.png">

**Comment by neon-balcony** [comment]
Mark it as closed because current Google Sheets API cannot afford query semantics required here.
