### ISSUE TITLE
ENV file missing

### ISSUE THREAD

**Issue by funthomas** [openblocks-dev/openblocks#5]
Hi

I am trying tutorial from https://docs.openblocks.dev/self-hosting
and after CMD docker-compose up  
service openblocks is still restarting 

in container logs was loged message

Init configuration
rm: cannot remove '/env/application-selfhost.yml': No such file or directory

perhaps something with ENV files is missing in tutorial ?

**Comment by neon-balcony** [comment]
@funthomas Hi, thanks for reporting this issue, we're currently working on it. A new image will be published soon.

**Comment by funthomas** [comment]
problem solved, thanks
