### ISSUE TITLE
Filter table optional case-sensitive 

### ISSUE THREAD

**Issue by TychoCeltCast** [openblocks-dev/openblocks#50]
Hi,

I would like for the option to enable/disable case sensitive in the filter for the table
Currently, it is case-sensitive.
<img width="621" alt="Scherm­afbeelding 2022-11-19 om 13 23 59" src="https://user-images.githubusercontent.com/107351632/202850696-55aa7d7f-83a9-4ad3-9bd8-f7bcb24c58db.png">
<img width="630" alt="Scherm­afbeelding 2022-11-19 om 13 23 54" src="https://user-images.githubusercontent.com/107351632/202850698-20355f27-00a4-4cba-82ba-fd67823248b5.png">

**Comment by neon-balcony** [comment]
Great suggestion! we've put it in our backlog.

**Comment by agaitan026** [comment]
👍

**Comment by neon-balcony** [comment]
Closed as feature supported in latest version.
