### ISSUE TITLE
Query execution error: http:; nested exception is java.net.UnknownHostException: http:.

### ISSUE THREAD

**Issue by architectdrone** [openblocks-dev/openblocks#51]
Hello, I am attempting to connect to a REST service that is running locally on post 8080. (I am using the localhost workaround of using  host.docker.internal) When I attempt to connect, I get this error message:

> Query execution error: http:; nested exception is java.net.UnknownHostException: http:.

Here's what that looks like in the Query editor...

![image](https://user-images.githubusercontent.com/17835256/202863406-de8f7ac6-034c-4452-9774-f0b7f1c705c7.png)

I tried connecting to the REST service through other means, and it worked. Furthermore, I see no indication that the service is being hit by examining the logs. So, I do not think this is an issue with the service.

I tried a couple of different things:

 - tried with https instead of http, no luck
 - tried omitting 8080, no luck

**Comment by sarike** [comment]
The rest api than can works in Openblocks must be public to the network. Because it will be requested from Openblocks' backend server.

You can deploy or proxy(e.g. SSH) your local service on a server with public network. And input the public server's ip in Openblocks.

We'll also explore how to make this scene more friendly.

**Comment by neon-balcony** [comment]
Hi @architectdrone ,

I think it is be a 'slash' missing issue😂 . See my test result attached:

I have a test api on my localhost:
![image](https://user-images.githubusercontent.com/118174126/202887580-5e00ad6b-8cc7-4bde-aca2-a6d5fd537e35.png)


Request it with a REST-API data source using host.docker.internal (for my mac, other systems see this [docs](https://docs.openblocks.dev/self-hosting/access-local-database-or-api)):
![image](https://user-images.githubusercontent.com/118174126/202887560-e658117c-0e03-4964-9e53-0453c6fd2eb5.png)

After adding the missing '/':
![image](https://user-images.githubusercontent.com/118174126/202887565-18ec0dfc-ac14-4477-a317-c5efd3a9f5c9.png)

**Comment by architectdrone** [comment]
Very nice, problem solved. 👍 One suggestion... the text highlighting is
somewhat confusing. When it shows up in red, that communicates to me that a
slash will be added automatically...

Regardless, thanks 😀
