### ISSUE TITLE
REST query sending empty body to server

### ISSUE THREAD

**Issue by architectdrone** [openblocks-dev/openblocks#53]
I have a REST service running on localhost:8080. I am able to hit the /query endpoint from Postman, like this

![image](https://user-images.githubusercontent.com/17835256/202930588-d8566566-ffa1-44d4-9b55-7d4286dcfc8c.png)

When I do this, in the terminal of the webapp, I see that I have recieved the message, as is expected...

```
2022-11-20 16:47:59.468 DEBUG 11680 --- [nio-8080-exec-1] o.a.coyote.http11.Http11InputBuffer      : Received [GET /query HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.8
Postman-Token: 1e7b5fca-e73d-4759-8c7b-4fe91c8cc560
Host: host.docker.internal:8080
Connection: keep-alive
Content-Length: 4

abcd]
```

However, when I attempt the exact same thing from OpenBlocks, like this...

![image](https://user-images.githubusercontent.com/17835256/202930748-ebf7f654-35cb-4900-a734-6abf36ac699f.png)

I do not receive the body of the message 😕

```
2022-11-20 16:48:46.071 DEBUG 11680 --- [nio-8080-exec-2] o.a.coyote.http11.Http11InputBuffer      : Received [GET /query?= HTTP/1.1
user-agent: ReactorNetty/1.0.24
host: host.docker.internal:8080
accept: */*
content-type: application/json
content-length: 0

]
```

A few notes:
 - Yes, I know that I used application/json and didn't send json 😀 This also fails when I use properly formatted json - I didn't include the json because it has personally identifiable information, however, if you think that it would be useful, I will do a demonstration of it with some redacted information
 - There is a chance, however small, that this is a weird problem with docker, however, I have not been able to confirm either way, because I couldn't get a dev environment set up locally 😟 I tried my best but I couldn't figure it out, lol! 

Thanks, I am a huge fan of the project!!

**Comment by neon-balcony** [comment]
Hi @architectdrone , 

Please try set your HTTP method to POST
![image](https://user-images.githubusercontent.com/118174126/202975465-7aa5aec0-cff2-4eee-8999-9aa617184b67.png)

For setting up the dev environment locally, we're writing a documentation for that, sorry about the inconvenience.

**Comment by architectdrone** [comment]
LOL that makes sense... well, sort of, maybe the body field should be disabled when GETing?

Also thanks for looking into that!

**Comment by architectdrone** [comment]
LOL that makes sense... well, sort of, maybe the body field should be disabled when GETing?

Also thanks 😀
