### ISSUE TITLE
Field type password.

### ISSUE THREAD

**Issue by leoborlot** [openblocks-dev/openblocks#54]
Hi people.

I testing to build an apkiccation withyou platform, and i dont find the field type where we hidde the cheracters, i think so i need a field type password.

**Comment by neon-balcony** [comment]
Hi @leonardoborlot ,

Thanks for the post, I believe this component can solve your issue.
![image](https://user-images.githubusercontent.com/118174126/202976532-67e537be-8cbc-4146-8f6d-8d0781ca9786.png)

**Comment by leoborlot** [comment]
Thanks
