### ISSUE TITLE
Bug? In edti mode, when i selec the button its execute click in, 

### ISSUE THREAD

**Issue by leoborlot** [openblocks-dev/openblocks#55]
When i selec5 the butt9n in edit mode, the button execute the click, i think so, the mostusual is, in edito mode the form canrt to be submitted and the clicks dont have effects.

**Comment by neon-balcony** [comment]
Hi @leonardoborlot ,

This is a by default behavior, editors in editing the app also act as an end user. So for now there're two ways if you want to focus the button without triggering events:
- Click on the corner tab of the button 
- Or, hold on CMD (mac) / CTRL (windows/linux) first, then click the button
![image](https://user-images.githubusercontent.com/118174126/202982983-dab514fa-dbcb-40dc-ad98-2538475d3e86.png)
