### ISSUE TITLE
Can't edit component names on Safari

### ISSUE THREAD

**Issue by m4rcelpl** [openblocks-dev/openblocks#56]
Hi!

On Safari 16.1 (18614.2.9.1.12) when I try to change component name, nothing happen. In console we can see error.
On Brawe it is work fine. 

<img width="474" alt="Zrzut ekranu 2022-11-21 o 09 44 58" src="https://user-images.githubusercontent.com/13198386/203005884-51ee31d7-f312-4d03-acb1-61967f9c192b.png">

**Comment by sarike** [comment]
Thanks for your post. It's a browser compatibility Issues. We'll fix it soon. Until then you can use Chrome/Firefox instead.
