### ISSUE TITLE
limit is capped at 100kb

### ISSUE THREAD

**Issue by FrankoFM** [openblocks-dev/openblocks#59]
I am sending a REST POST request to my API containing a file from the "File Upload" component.
My API is making use of `app.use(bodyParser.json({ limit: "100mb" }));` so it shouldn't be a problem on my end.
DevTools is giving me: `Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)`
So I'm asuming that its limited on openblocks end.

I am using the local Docker version.

**Comment by FrankoFM** [comment]
Here is something to reproduce

API Server:
```js
import express from "express";

const app = express();

app.use(express.json({ limit: "100mb" }));

app.route("/").post((req, res) => {
    console.log(req.body);
});

app.listen(8080, () => {
    console.log("test api is running");
});
```

Openblocks Export:
```json
{
    "applicationInfo": {
        "name": "reproduce",
        "createAt": 1669226377786,
        "createBy": "637e0a555b80d70c68755489",
        "applicationId": "637e5f895fa8b6790715265d",
        "applicationType": 1
    },
    "applicationDSL": {
        "ui": {
            "layout": {
                "bdfdabb3": { "i": "bdfdabb3", "h": 5, "w": 5, "x": 0, "y": 0 }
            },
            "items": {
                "bdfdabb3": {
                    "compType": "file",
                    "comp": {
                        "text": "Browse",
                        "uploadType": "single",
                        "fileType": "",
                        "showUploadList": true,
                        "disabled": "",
                        "onEvent": [
                            {
                                "name": "change",
                                "handler": {
                                    "compType": "executeQuery",
                                    "comp": { "queryName": "query1" },
                                    "condition": "",
                                    "slowdown": "debounce",
                                    "delay": ""
                                }
                            }
                        ],
                        "style": {
                            "background": "",
                            "border": "",
                            "radius": "",
                            "text": "",
                            "accent": ""
                        },
                        "minSize": "",
                        "maxSize": "",
                        "maxFiles": "",
                        "formDataKey": "",
                        "hidden": ""
                    },
                    "name": "file1"
                }
            }
        },
        "queries": [
            {
                "compType": "restApi",
                "comp": {
                    "bodyType": "application/json",
                    "body": "{{file1.value}}",
                    "httpMethod": "POST",
                    "path": "http://host.docker.internal:8080",
                    "headers": [
                        { "key": "Content-Type", "value": "application/json" },
                        { "key": "", "value": "" }
                    ],
                    "params": [{ "key": "", "value": "" }],
                    "bodyFormData": [{ "key": "", "value": "", "type": "text" }]
                },
                "id": "uehg2n8j8fmlndks8ozw9emo",
                "name": "query1",
                "order": 1669226648628,
                "datasourceId": "637e0a555b80d70c6875548b",
                "triggerType": "manual",
                "onEvent": [],
                "notification": {
                    "showSuccess": true,
                    "success": { "text": "" },
                    "showFail": true,
                    "fail": [{ "text": "", "condition": "" }],
                    "duration": ""
                },
                "timeout": "",
                "confirmationModal": {
                    "showConfirmationModal": false,
                    "confirmationMessage": ""
                },
                "periodic": false,
                "periodicTime": ""
            }
        ],
        "tempStates": [],
        "transformers": [],
        "hooks": [
            { "compType": "urlParams", "comp": {}, "name": "url" },
            { "compType": "momentJsLib", "comp": {}, "name": "moment" },
            { "compType": "lodashJsLib", "comp": {}, "name": "_" },
            { "compType": "utils", "comp": {}, "name": "utils" },
            { "compType": "message", "comp": {}, "name": "message" },
            { "compType": "localStorage", "comp": {}, "name": "localStorage" },
            { "compType": "currentUser", "comp": {}, "name": "currentUser" }
        ],
        "settings": {
            "maxWidth": { "dropdown": "1920", "input": "" },
            "themeId": "default"
        },
        "preload": { "libs": [], "script": "", "css": "" }
    }
}
```

**Comment by neon-balcony** [comment]
Hi @FrankoFM,

Thanks for the report, we're checking on this. Just to make it clear, how big is the file size you wish to send with Openblocks REST?

**Comment by FrankoFM** [comment]
> Hi @FrankoFM,
> 
> Thanks for the report, we're checking on this. Just to make it clear, how big is the file size you wish to send with Openblocks REST?

Currently, around 50kb - 5mb. But would be good if the user could set up the limit. Or something like an env variable for the hoster.

**Comment by neon-balcony** [comment]
Strange, 5MB should be fine, could you please post a snapshot of the request and error response in DevTools?

**Comment by FrankoFM** [comment]
## 1kb:
request:
<img src="https://i.ibb.co/X3Dysbt/1kb-1.png"></img>
server:
<img src="https://i.ibb.co/SmjjvVF/1kb.png"></img>

## 50kb:
request:
<img src="https://i.ibb.co/mqJzyST/50kb-1.png"></img>
server:
<img src="https://i.ibb.co/qdpPvqx/50kb.png"></img>

## 1mb:
request:
<img src="https://i.ibb.co/WD9D2wK/1mb-2.png"></img>
devtools error:
<img src="https://i.ibb.co/Zg16xrM/1mb-1.png"></img>

**Comment by FrankoFM** [comment]
Since you are using axios on the clientside I think that could be the problem.
[Maybe kinda related?](https://stackoverflow.com/questions/58655532/increasing-maxcontentlength-and-maxbodylength-in-axios)

**Comment by neon-balcony** [comment]
Okay I got that, currently Openblocks uses a Nginx to proxy all requests in docker image, and the default payload size for that is 1 MB unfortunately :sweat_smile:.

For now you can follow the steps to update the Nginx limit: 
1. log into Openblocks docker container
2. edit `/openblocks/nginx/nginx-root.conf.template` file
<img width="427" alt="image" src="https://user-images.githubusercontent.com/118174126/203785471-141e2afd-015d-4fdb-b7af-4706feb0057c.png">

3. set `client_max_body_size` under `http` module, say 20m for the demo
<img width="813" alt="image" src="https://user-images.githubusercontent.com/118174126/203785692-72092942-d715-440d-9ff8-60350180b5ac.png">

4. save your update and restart your container, it should be fine then for your cases.


Also many thanks about the user-defined limit request, we'll add that soon, maybe next release :smile:	


========= Updated, still one more config needs to be updated, sorry about that

1. Go to your workspace where Openblocks is deployed (`~/workspace` in my case), go to `cd ./stacks/configuration`
![image](https://user-images.githubusercontent.com/118174126/203976434-5ea69e1a-b8ad-4665-a459-90ad4807db8b.png)

2. edit `application-selfhost.yml`, add setting for `spring.codec.max-in-memory-size` as below (20MB, same as above), this setting is used by Spring webflux to handle http requests.
![image](https://user-images.githubusercontent.com/118174126/203979053-d3eadafb-1c66-4913-8025-76136294c4e2.png)

3. Finally, save and restart your container

**Comment by FrankoFM** [comment]
Thank you very much! Keep it up! :)
