### ISSUE TITLE
Switching to GPL instead of AGPL?

### ISSUE THREAD

**Issue by kedarv** [openblocks-dev/openblocks#6]
I'd love to try this out internally in my organization, but AGPL isn't usually popular in commercial orgs (if not outright banned for internal use). Curious if y'all evaluated AGPL vs more permissive licensing (GPL/MIT/etc)

**Comment by hanshuai** [comment]
From our understanding, AGPL is just GPL for network server software. Why is your organization discouraging AGPL? We’ll reevaluate it definitely if the license issue harms the community.

**Comment by ianmacartney** [comment]
Maybe a dumb question, but if I build an internal app using OpenBlocks, do I have to open source the app itself, referring to all our internal tables & such? Even if I don't modify the openblocks code? I'm shy to expose our company's internal tooling publicly. And out of curiosity, if I built a more public-facing app using OpenBlocks, would that need to be open sourced? If so, what does that look like for something built in an IDE? Copying the JSON config somewhere?

**Comment by kedarv** [comment]
I think this thread has some more context: https://news.ycombinator.com/item?id=21915649
essentially the viral nature of AGPL "over the network" prevents my org from allowing AGPL code internally or externally - whether or not this is intended or not is up to you :)

I think GPLv3 is weaker in this sense, which is why it's usually more allowable

**Comment by hanshuai** [comment]
> Maybe a dumb question, but if I build an internal app using OpenBlocks, do I have to open source the app itself, referring to all our internal tables & such? Even if I don't modify the openblocks code? I'm shy to expose our company's internal tooling publicly. And out of curiosity, if I built a more public-facing app using OpenBlocks, would that need to be open sourced? If so, what does that look like for something built in an IDE? Copying the JSON config somewhere?

An essential precondition of GPL/AGPL is that you modified the software (i.e. Openblocks). If you don't modify the software, then you don't have to worry about licensing.
When you use Openblocks to build your apps, there are no limits to what you can do with those apps. You can share them, sell them, and all of that is completely fine.

**Comment by ianmacartney** [comment]
Thank you, that makes sense.

**Comment by hanshuai** [comment]
A short explanation about AGPL:
* if you didn't modify the software, no worries about the license.
* if you modified it, but use it internally, there is no limit.
* if you modified and provided it to your customers, the modification should be open-source too.

**Comment by kedarv** [comment]
> A short explanation about AGPL:
> 
> * if you didn't modify the software, no worries about the license.
> * if you modified it, but use it internally, there is no limit.
> * if you modified and provided it to your customers, the modification should be open-source too.

Yep I think that's correct, but unfortunately a lot of legal departments don't see the benefits of AGPL code vs. potential risks (eg. https://opensource.google/documentation/reference/using/agpl-policy - I don't work at Google but my employer has a very similar text regarding AGPL)

Totally fine to leave this as AGPL and close the issue out, just wanted to flag it :)

**Comment by KrishnaPG** [comment]
> A short explanation about AGPL:
> 
> * if you didn't modify the software, no worries about the license.
> * if you modified it, but use it internally, there is no limit.
> * if you modified and provided it to your customers, the modification should be open-source too.

Missed the most important one: 
* you have to open-source all the rest of your code too (anything and everything that the AGPL/GPL touches).

This condition is the one that causes the main problem and why many stay away from AGPL/GPL.

In that sense `Retool` is much better alternative, since it does not force one to release one's private code.

OpenBlocks is being positioned as 'open source' alternate of Retool, but the AGPL/GPL is doing more harm than good, as it prevents major adoption.

Please reconsider the license.
