### ISSUE TITLE
Couchdb

### ISSUE THREAD

**Issue by billyrudi** [openblocks-dev/openblocks#61]
Hi, can you provide the Couchdb Data Sources?
Good job! i like your project!

**Comment by YoJayz** [comment]
@billyrudi Hi Paolo, in the latest Openblocks [v1.1.6](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.6) release, we support CouchDB database. Please check it out!

**Comment by billyrudi** [comment]
perfect thanks!
