### ISSUE TITLE
how use localstorage?

### ISSUE THREAD

**Issue by agaitan026** [openblocks-dev/openblocks#65]
Hi im trying to use localstorage, how i create one?

with this value

const items = {{localStorage.dataLocalStorage}} ?? [];
items.push({
  id: {{ Date.now() }},
	Name: {{ ui.product.value }},
  Quantity: {{ ui.quantity.value }},
})
return items;

**Comment by sarike** [comment]
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/1788906/203892049-344b1578-d5f7-4334-a025-69199bd5d650.png">

In pure javascript editor (e.g.  JS Query, Run JavaScript Action),  `{{}}` is not needed.

**Comment by agaitan026** [comment]
works, i have my mind in retool yet :( sorry, and how to populate a table with that info? 

![image](https://user-images.githubusercontent.com/56446006/203892903-46518a98-44d1-491b-b204-bf9f7d5280a1.png)

my theory is every time i select option and press Button it should add a new row on localstorage array and show it in the DB

**Comment by lmx1117** [comment]
> works, i have my mind in retool yet :( sorry, and how to populate a table with that info?
> 
> ![image](https://user-images.githubusercontent.com/56446006/203892903-46518a98-44d1-491b-b204-bf9f7d5280a1.png)
> 
> my theory is every time i select option and press Button it should add a new row on localstorage array and show it in the DB
> 
> i tried this localStorage.getItem('dataLocalStorage');
> 
> ![image](https://user-images.githubusercontent.com/56446006/203894633-2db849f6-3a78-494b-b686-d74ae240ccd3.png)
> 
> but not working

try this
![image](https://user-images.githubusercontent.com/116335720/203896188-c7cff2a1-5b2a-4ff9-a527-c6011a6f863f.png)

**Comment by agaitan026** [comment]
> > works, i have my mind in retool yet :( sorry, and how to populate a table with that info?
> > ![image](https://user-images.githubusercontent.com/56446006/203892903-46518a98-44d1-491b-b204-bf9f7d5280a1.png)
> > my theory is every time i select option and press Button it should add a new row on localstorage array and show it in the DB
> > i tried this localStorage.getItem('dataLocalStorage');
> > ![image](https://user-images.githubusercontent.com/56446006/203894633-2db849f6-3a78-494b-b686-d74ae240ccd3.png)
> > but not working
> 
> try this ![image](https://user-images.githubusercontent.com/116335720/203896188-c7cff2a1-5b2a-4ff9-a527-c6011a6f863f.png)

i see, so in component i can use {{}}

**Comment by agaitan026** [comment]
works but see this https://www.loom.com/share/1b46ee31299d42f2aba1ae53d644b43d that behaviour the table is not getting updated when localstorage loads, is that normal?

**Comment by lmx1117** [comment]
Yes we usually write JS code in {{}}, and sorry for the typo in the pic, for this, you need to refresh to see the "push" content, or,  you can use temporary state to get real time refresh

> works but see this https://www.loom.com/share/1b46ee31299d42f2aba1ae53d644b43d that behaviour the table is not getting updated when localstorage loads, is that normal?

**Comment by agaitan026** [comment]
> Yes we usually write JS code in {{}}, and sorry for the typo in the pic, for this, you need to refresh to see the "push" content, or, you can use temporary state to get real time refresh
> 
> > works but see this https://www.loom.com/share/1b46ee31299d42f2aba1ae53d644b43d that behaviour the table is not getting updated when localstorage loads, is that normal?

any example?

**Comment by lmx1117** [comment]
> > Yes we usually write JS code in {{}}, and sorry for the typo in the pic, for this, you need to refresh to see the "push" content, or, you can use temporary state to get real time refresh
> > > works but see this https://www.loom.com/share/1b46ee31299d42f2aba1ae53d644b43d that behaviour the table is not getting updated when localstorage loads, is that normal?
> 
> any example?

Please check this demo, and the temporary state doc will be online soon [Pagination with temporary state demo](https://cloud.openblocks.dev/apps/6379cdd9f02c6e6ecc1d37ff/view)

**Comment by agaitan026** [comment]
So instead of local storage use temp state?there any code for me to test?

**Comment by lmx1117** [comment]
> So instead of local storage use temp state?there any code for me to test?

Maybe you could try something like this:
![image](https://user-images.githubusercontent.com/116335720/203983617-b21a66b6-f2ca-4e6e-8006-71602a66e51d.png)
![image](https://user-images.githubusercontent.com/116335720/203983741-4fca670d-ff62-47ab-affc-00f63df7eb01.png)
‘’‘
const items = state1.value
state1.setIn([state1.value.length], { "id": Date.now(), "Name": select1.value })
return items.value
’‘’

**Comment by agaitan026** [comment]
> > So instead of local storage use temp state?there any code for me to test?
> 
> Maybe you could try something like this: ![image](https://user-images.githubusercontent.com/116335720/203983617-b21a66b6-f2ca-4e6e-8006-71602a66e51d.png) ![image](https://user-images.githubusercontent.com/116335720/203983741-4fca670d-ff62-47ab-affc-00f63df7eb01.png) ‘’‘ const items = state1.value state1.setIn([state1.value.length], { "id": Date.now(), "Name": select1.value }) return items.value ’‘’

With that how do I erase the state variable? For example when I got two or more users using the same module , I don't want user1 to see user3 items you know what I mean? I will have 4 user working or creating stock transfer documents I need to separate them by user created by. Not user if that's possible with openblocks?

**Comment by neon-balcony** [comment]
Hi @agaitan026,

The temporary state is kept in the browser's memory of each end user, so data are naturally separated for them.

**Comment by neon-balcony** [comment]
> 

See `currentUser` in **Globals**, it represents current visitor. You can find user's id and name in Openblocks.
![image](https://user-images.githubusercontent.com/118174126/203986719-ce6a678f-efa7-47b3-9155-4a4d9cd98047.png)

If you wish to track it with Openblocks' user id, you can join the id with `Query workspace users` in `Openblocks API` later.
![image](https://user-images.githubusercontent.com/118174126/203987053-45d7ae45-d1bc-42dc-8b06-3d0ccd32c0b9.png)

**Comment by agaitan026** [comment]
Woh awesome so I can get that value and save it to my own MySQL db

**Comment by agaitan026** [comment]
and that temp state can be cleared after another button is clicked?

**Comment by lmx1117** [comment]
> and that temp state can be cleared after another button is clicked?

Yes you can control it by setting button's event, of course, the page refresh will also automatically clear the temporary state, please check our doc here [https://docs.openblocks.dev/build-apps/write-javascript/temporary-state](https://docs.openblocks.dev/build-apps/write-javascript/temporary-state)
