### ISSUE TITLE
S3 storage support

### ISSUE THREAD

**Issue by agaitan026** [openblocks-dev/openblocks#66]
Hi one very important thing will be S3 integration, thats basically for me one stop that doesnt let me move from retool :(

**Comment by agaitan026** [comment]
Any eta?

**Comment by lmx1117** [comment]
[https://github.com/orgs/openblocks-dev/projects/1/views/1](https://github.com/orgs/openblocks-dev/projects/1/views/1)
It's already in our roadmap, being processed now😉

**Comment by agaitan026** [comment]
ty

**Comment by agaitan026** [comment]
Any eta? I saw its for next year?

**Comment by agaitan026** [comment]
hi @lmx1117  this is for next year?

**Comment by neon-balcony** [comment]
@agaitan026 ,

Hi, S3 is a widely used data storage, we'll plan to support it in Jan 2023 😬

**Comment by Simonaaaa-C** [comment]
Hi, we now support S3! Please check and update to the latest version v1.1.4. Thanks for your advice and patience!
