### ISSUE TITLE
Confusing message about localhost when making a new data source on a local installation of OpenBlocks

### ISSUE THREAD

**Issue by architectdrone** [openblocks-dev/openblocks#7]
The message is:

> The code maker image uses Bridge mode by default, so it cannot access host services through 127.0.0.1/localhost. To access host services, see

See what, exactly? Was there supposed to be a link to documentation?

**Comment by hanshuai** [comment]
try this thread https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container

**Comment by hanshuai** [comment]
we'll write a doc about it soon

**Comment by lmx1117** [comment]
docs has updated now~~: [https://docs.openblocks.dev/self-hosting/access-local-database-or-api](https://docs.openblocks.dev/self-hosting/access-local-database-or-api)

**Comment by lmx1117** [comment]
> The message is:
> 
> > The code maker image uses Bridge mode by default, so it cannot access host services through 127.0.0.1/localhost. To access host services, see
> 
> See what, exactly? Was there supposed to be a link to documentation?


docs has updated now~~: https://docs.openblocks.dev/self-hosting/access-local-database-or-api
