### ISSUE TITLE
Ability to search Tree Select component, similar to Cascader

### ISSUE THREAD

**Issue by ronen770** [openblocks-dev/openblocks#81]
It would be great if we had the ability to search/filter through the tree select, the same as we can right now with the Cascader component. 

I would love to contribute, however I am not that familiar with frontend code, so Ive become a bit lost trying to understand how to add this ability myself.

Thanks
Ronen

**Comment by lmx1117** [comment]
Hi Ronen, thanks for reaching out with this! This is an enhancement and we have put it in the backlog now~~

**Comment by lmx1117** [comment]
Hi ronenbuz, this issue is already solved, please check it out, and thanks again for your advice and patience. 😉

**Comment by ronen770** [comment]
Great thank you, I will now!
