### ISSUE TITLE
Receiving CORS issues on Query library page (Cloud)

### ISSUE THREAD

**Issue by armx84** [openblocks-dev/openblocks#86]
Greetings
Great project!
I was trying to add Rest API queries in the Query library page but I'm getting "Failed to parse REST API query configuration".
Upon further investigation I realized it's a CORS issue. In the Console I have:

`Access to XMLHttpRequest at 'https://api.openblocks.dev/api/library-queries/63874c9175cfb658566106b5' from origin 'https://cloud.openblocks.dev' has been blocked by CORS policy: Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.
index.8d8d6801.js:230 XMLHttpRequest
M9r @ index.8d8d6801.js:230
index.8d8d6801.js:230 update library query error:  Error: Failed to connect to server, please check your network
    at Xge (index.8d8d6801.js:230:13362)
    at Ar (index.8d8d6801.js:230:13270)
    at E8r (index.8d8d6801.js:230:69872)
    at E8r.next (<anonymous>)
    at p (index.8d8d6801.js:230:1364)
    at A (index.8d8d6801.js:230:1930)
E8r @ index.8d8d6801.js:230
api.openblocks.dev/api/library-queries/63874c9175cfb658566106b5:1          Failed to load resource: net::ERR_FAILED`

I am using Google Chrome 107.0.5304.121 on MacOS. Tried with Safari, same issue.
Is it just me?

Thanks in advance

**Comment by neon-balcony** [comment]
Hi @stockaiz, 

Thanks for reporting this, could you help record a video or take snapshots for us for better understanding of the problem?

**Comment by armx84** [comment]
Sure.
The error appears upon each keystroke in the Parameters field. It seems it's making an XmlHTTPRequest that fails.
![image](https://user-images.githubusercontent.com/68891022/204810541-413d7c0a-fbb8-4445-9fff-0243ad2957bb.png)

Please note that I added the API URL and tested it with Postman and it works fine. Here I didn't provide the URL to show it gives error regardless.

Thanks!

**Comment by Esieve** [comment]
@stockaiz This is a weird issue, I wonder if there are any problems when you're editing an app or other operations? Because those APIs responses share the same CORS headers

**Comment by armx84** [comment]
Hi @Esieve , sorry for the late reply.
I have the same problem when I'm typing in the Data field of a table.
Basically the error appears every time I interact with queries. Am I the only one? I'm using the latest Chrome at the end of the day.

![image](https://user-images.githubusercontent.com/68891022/206362841-fbb0074d-7004-4f5e-a465-f29fab885c7b.png)

![image](https://user-images.githubusercontent.com/68891022/206362948-5eef8add-3720-4e77-b1f4-b88ec4cd25a5.png)

**Comment by armx84** [comment]
FYI I tested in Safari 16.1 and it works fine without any CORS error.
