### ISSUE TITLE
Possibility to change theme by code

### ISSUE THREAD

**Issue by billyrudi** [openblocks-dev/openblocks#88]
in real end user application it is usefull to let them to chnge between themes.
can you implement some method like 
utils.setTheme (theme-name)
utils.getGetThemes  ( from openblocks themes) return theme-name
utils.getCurrentUserTheme ( fom local storage ) return theme-name

thanks Paolo

**Comment by YoJayz** [comment]
@billyrudi Hi Paolo, thanks for your support and patience.
 
In the latest Openblocks v1.1.6 release, we add a new global variable `theme` and support method `theme.switchTo()`. Now you can **change app themes dynamically** with JS codes!

![image](https://user-images.githubusercontent.com/113571084/221153745-6b77813e-a8b5-4197-9093-9607a165ad92.png)

Here is a [demo](https://cloud.openblocks.dev/apps/63f84ca9f5f6f66102fedf3b/view) for you. Please check it out 😃

For more release notes, see [Openblocks releases](https://github.com/openblocks-dev/openblocks/releases).
