### ISSUE TITLE
[Feature Request] GraphQL Datasources

### ISSUE THREAD

**Issue by deathemperor** [openblocks-dev/openblocks#9]

**Comment by hanshuai** [comment]
GraphQL integration is in our roadmap. Please stay tuned for updates : )

**Comment by a-c-m** [comment]
+1 to this.

Also Is your roadmap public?

**Comment by hanshuai** [comment]
We'll be publishing our roadmap soon.

**Comment by voidberg** [comment]
Another +1 to this.

**Comment by lmx1117** [comment]
Hi everyone, GraphQL data source is available now, please check it out, and thanks again for your advice and patience. 😉

**Comment by ulbrich** [comment]
Hi there, while the integration feels really good, the data transmitted to the server has a flaw: Variables are no JSON but as string… 🙂 

See example here:

```{
  "variables": "{\"email\":\"foo@bar.com\",\"password\":\"too-many-secrets\"}",
  "query": "query authenticateByEmail($email: String!, $password: String!) {\n  authenticateByEmail(arg1: {email: $email, password: $password}) {\n    jwtToken\n  }\n}"
}
```

This would be correct:

```
{
  "variables": { "email": "foo@bar.com", "password": "too-many-secrets" },
  "query": "query authenticateByEmail($email: String!, $password: String!) {\n  authenticateByEmail(arg1: {email: $email, password: $password}) {\n    jwtToken\n  }\n}"
}
```

**Comment by lvhuichao** [comment]
> 

Hi @ulbrich , thanks for reporting this issue. We will fix it in the next version, please stay tuned.

**Comment by neon-balcony** [comment]
Hey @ulbrich , a [hot fix image](https://hub.docker.com/layers/openblocksdev/openblocks-ce/latest/images/sha256-b24577f0c0baa3a067931c6717107b723a6d4d75567fe402e00b9a5f944ad220?context=explore) for this issue has been published, please update Openblocks and give us a try 😄

**Comment by ulbrich** [comment]
Hi @neon-balcony, I can happily confirm that the fix works nicely communicating with Hasura using GraphQL queries. Thank you so much! 🎉
