### ISSUE TITLE
Retrieve or reset password (help)

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#90]
I might be missing something, but I dont see a way to reset or retrieve my password. 

![image](https://user-images.githubusercontent.com/296522/205328302-41b09d6f-01e1-429a-aba8-8269e74eff6f.png)

**Comment by neon-balcony** [comment]
Hi @swright-eti,

Currently for self-hosted instances you can update the password but cannot reset it, because there's no email server setup for sending a reset email. We're thinking about how to solve this, maybe a super admin that can reset any users password?

**Comment by TychoWerner** [comment]
> 

That seems like a logical choice.

**Comment by swright-eti** [comment]
I think thats a reasonable option.

**Comment by jimhuds** [comment]
> Hi @swright-eti,
> 
> Currently for self-hosted instances you can update the password but cannot reset it, because there's no email server setup for sending a reset email. We're thinking about how to solve this, maybe a super admin that can reset any users password?

Potentially SMTP settings if it's not too hard to implement?

**Comment by YoJayz** [comment]
Hi everyone. Workspace admins now can **reset member's password** in **solo workspace mode**.
Please check and update to the latest version [v1.1.5](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.5). Thanks for your suggestion and patience!

FYI, below are the steps:
1. Modify the yaml config file `stacks/configuration/application-selfhost.yml` to set your self-hosted Openblocks to **solo workspace mode**.
<img src="https://user-images.githubusercontent.com/113571084/217828203-224451da-3a67-4c9f-83de-37ef8b830658.png" width="80%">

2. Sign in and go to **Settings** -> **Members** page to reset member's password to a random one. 
<img src="https://user-images.githubusercontent.com/113571084/217828343-043847ad-2f8d-4f52-bc50-5bad963dea22.png" width="100%">
<img src="https://user-images.githubusercontent.com/113571084/217830826-5bdfc718-9150-46aa-939d-22f854701790.png" width="40%">

3. Members can then modify their passwords in the profile setting.
<img src="https://user-images.githubusercontent.com/113571084/217830179-93674ce6-8fd4-416c-ac88-a58403721a33.png" width="40%">
<img src="https://user-images.githubusercontent.com/113571084/217829214-2e690ba4-2fe1-4835-bacc-c45ae7dd4135.png" width="40%">

**Comment by unclesamwk** [comment]
Please help, how can i set the openblocks instance to "solo workspace mode". I dont unterstand ist. thx

**Comment by unclesamwk** [comment]
Please can anyone help me?
