### ISSUE TITLE
New feature request: Configure openblocks to use a different MongoDB instance

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#91]
I'd like to be able to provide connection and auth details at startup so that OpenBlocks could a difference instance of MongoDB. We already have MongoDB setup and its included in our disaster recovery and backup. It would be nice to have OpenBlock data stored in that instance of MongoDB to keep our backups simpler.

**Comment by neon-balcony** [comment]
Hi @swright-eti,

Thanks for the post, actually this is achievable, see the following steps:

1. Find where you start up Openblocks instance, and go to  `$PWD/stacks`.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/118174126/205420563-ff353a9e-b6ed-48e0-a998-a7e65c0e4424.png">
2. Go to `configuration` folder, under where you should see `application-selfhost.yml`.
<img width="258" alt="image" src="https://user-images.githubusercontent.com/118174126/205420584-8a952a82-1ab8-46bc-b2fa-0c1f103c932f.png">
3. open and edit `application-selfhost.yml`, here you can replace MongoDB/Redis connection URI string with your own.
<img width="813" alt="image" src="https://user-images.githubusercontent.com/118174126/205420535-80d884e9-c2a6-4814-833f-39d8ab8fed88.png">

To make things clear, in Openblocks we uses 
- MongoDB as data persistence layer to store all data of settings, workspaces, users, apps and etc. 
- Redis as an distributed cache to store user sessions info for better performance, where AOF is enabled by default

4. Restart Openblocks container and then you should see Openblocks-related collections created under your MongoDB instances

A documentation about these steps is on the way, sorry about the inconvenience for now.

**Comment by swright-eti** [comment]
This is great, thank you. 
No that I know this is a spring app, presumably I can set those values through environment variables. Is that correct? That actually dovetails with how I'd like to configure this through a Helm Chart. 
I started working on a Chart for Open Blocks on Friday. If I can get it to work I will share it with with you.

**Comment by neon-balcony** [comment]
Yes the infrastructure for the backend used Spring webflux (Put simply, Spring boot + project reactor), so those values can be set through environment variables, we'll add a documentation for that soon.

**Comment by swright-eti** [comment]
Ok perfect, thanks.

**Comment by swright-eti** [comment]
I think I might be doing something wrong here. I tried to go the ENV route because its more flexible. I set the URI in the docker-compose file like this:

```
    environment:
      - LOCAL_USER_ID = swright
      - SPRING_DATA_MONGODB_URI = mongdodb://USER:PASSWORD@betadb1.dev.eti.software:27017/openblocks?socketTimeoutMS=5000
```

When the application starts up I can see that the container has the environment variables:

```
(⎈|beta:openblocks)swright@dev-09:~/workspace/openblocks-run$ docker exec -it openblocks env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=7d6e8e3d352b
TERM=xterm
LOCAL_USER_ID = swright
SPRING_DATA_MONGODB_URI = mongdodb://REDACTED:REDACTED@betadb1.dev.eti.software:27017/openblocks?socketTimeoutMS=5000
OPENBLOCKS_SERVER_PROXY_PASS=http://localhost:8080
HOME=/root
(⎈|beta:openblocks)swright@dev-09:~/workspace/openblocks-run$ 
```

I dont see a database getting created in betadb1.dev
I execed into the container and I can see that the mongo running in there is being used for storage because I can see the user I just created in the user collection. 

Does the environment have to have a different name? I might be translating the YAML incorrectly.

**Comment by neon-balcony** [comment]
Hi @swright-eti , 

For environment variables, please refer to its key name in this format:
![0bccfb55-9aee-4604-bd2f-ddf11a22bd9a](https://user-images.githubusercontent.com/118174126/205806950-8f9dd4de-9320-44f0-bd69-2ba3b4ff6c9e.jpeg)

So to config your MongoDB URI it should be:
```
MONGODB_URI=mongdodb://REDACTED:REDACTED@betadb1.dev.eti.software:27017/openblocks?socketTimeoutMS=5000
```

**Comment by swright-eti** [comment]
I have changed the key to MONGODB_URI. 
When the app starts up I am getting notified of an error. I tried to set the logging level but I must be using the wrong package. 

![image](https://user-images.githubusercontent.com/296522/205928945-f7c4ac17-cc28-40ec-9d1f-85744ab89aa5.png)

**Comment by swright-eti** [comment]
Thanks for that info. I have updated the name of the environment variable, but still no joy. 
When I create a user I see it being created in the MongoDB in the container. 


![image](https://user-images.githubusercontent.com/296522/205939323-53886086-8fbd-42af-88aa-b48f048cc447.png)

**Comment by neon-balcony** [comment]
Hi @swright-eti ,

I notice there are several issues in your docker YAML file:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/118174126/206199702-e8b46097-72a1-45af-9cb1-f390e25ca156.png">

1. LOCAL_USER_ID should be a number.
2. There is a typo in `mongdodb://`, should be like `mongodb://`.
3. I suspect you are using `docker-compose restart` to restart Openblocks, actually you need to call `docker-compose up` to recreate the container so that your new configurations can take effect.


We've updated our [documentation](https://docs.openblocks.dev/self-hosting#customize-deployment-configurations) for these notes above, thanks to your patience for helping us finding issues:grinning:.

**Comment by swright-eti** [comment]
Well that's embarrassing, thanks for pointing that out.  `mongdodb://`

When you say number, I assume you are referring to the user's UID. Is that right?

**Comment by swright-eti** [comment]
I am still doing something wrong. I fixed the spelling mistake in the URI, and changed the user ID. I took down the docker service, deleted the docker containers and images, and then deleted the stacks directory. 
I use docker compose up -d to start the service and I see that its pulling the image. Once its up, I create a new user account. Then I checked in mongo on betadb1. I dont see a database for openblocks. When I exec into the openblocks container I see that there is a user record in the openblocks database. 

How do I set the logging level properly?

![image](https://user-images.githubusercontent.com/296522/206214533-979296ae-eb66-4360-a263-4d1325388a1c.png)

**Comment by jerry-goodman** [comment]
Hi @swright-eti

**Comment by jerry-goodman** [comment]
Hi @swright-eti 
1. It is recommended that there is no white space between the environment key and the equal sign, for example 
 `- MONGODB_URI=xxx`
3. Make sure that the MongoDB user `cbclient` has permission to create a database
4. See what error is reported in the log `stacks/logs/backend/backend.log`

**Comment by swright-eti** [comment]
I removed the spaces as directed, but that still did not solve the problem. I had to add the authSource parameter. 

`MONGODB_URI=mongodb://REDACT:REDACT@betadb1.dev.eti.software:27017/openblocks?socketTimeoutMS=5000&authSource=admin`

This now works correctly. 

Thanks.
