### ISSUE TITLE
Bug: Can't access navigation menu item properties if label is empty

### ISSUE THREAD

**Issue by rainyclouds** [openblocks-dev/openblocks#92]
Steps to recreate:
1. On Openblocks homepage, click New and select Navigation to create a navigation page.
2. Click on Menu Item 1 to edit properties
3. Delete all text from label
4. Click X or anywhere outside to close edit dialog

Version: 1.1.1-95de3f4 self-hosted docker
Firefox 107.0.1 (64-bit)

Only workaround that I could find is to delete and recreate but that also deletes all sub-menu items.

**Comment by ggbond2077** [comment]
Thanks for your report, we will fix it soon.

**Comment by ggbond2077** [comment]
> 


Thanks for your report, we will fix it soon.

**Comment by lmx1117** [comment]
Hi rainyclouds, this issue is already solved, please check it out, and thanks again for your advice and patience. 😉
