### ISSUE TITLE
Question: OAUTH integration with Keycloak

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#93]
We use [Keycloak ](https://www.keycloak.org/docs/latest/server_admin/ )as an IDP. Is it possible to configure OpenBlocks to use Keycloak for user authentication and authorization?

**Comment by neon-balcony** [comment]
Hi @swright-eti , 

Thanks for reporting this, we'll add that in our backlog, please stay tuned!

**Comment by swright-eti** [comment]
Awesome, thank you.

**Comment by hanqyu** [comment]
I'm really looking forward to this!

**Comment by lvhuichao** [comment]
Hi @swright-eti @hanqyu , we now support configuring to use Keycloak for user authentication. Please try it.
https://hub.docker.com/r/openblocksdev/openblocks-ee
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/33057362/224632474-1ba87289-9d34-4a0a-9bef-c92be33b2d66.png">
<img width="560" alt="image" src="https://user-images.githubusercontent.com/33057362/224632665-e468014d-e68e-489e-a16c-e497c1c68305.png">

**Comment by sochacki111** [comment]
Hello @lvhuichao, I see that Keycloak integration is labeled as "Premium". How can I get premium access ? as I cannot find any information on your website.

> Hi @swright-eti @hanqyu , we now support configuring to use Keycloak for user authentication. Please try it. https://hub.docker.com/r/openblocksdev/openblocks-ee <img alt="image" width="1362" src="https://user-images.githubusercontent.com/33057362/224632474-1ba87289-9d34-4a0a-9bef-c92be33b2d66.png"> <img alt="image" width="560" src="https://user-images.githubusercontent.com/33057362/224632665-e468014d-e68e-489e-a16c-e497c1c68305.png">
