### ISSUE TITLE
Native icon support in text component or labels

### ISSUE THREAD

**Issue by neshorg** [openblocks-dev/openblocks#95]
Hello, I was wondering if we can use the same icons from buttons (e.g. prefix or suffix) in other components as well (or any text/label field option available in any component)?

When trying to copy & paste the icon from button prefix field into text component value I'll get the text representation of the icon:
{{ "/icon:solid/Close" }} instead of the icon itself.

As a work-around I've used the windows standard icons, but those don't go well in the same theme as the awesome icons you've already provided for other components (button, toggle and so on).

**Comment by lmx1117** [comment]
Unlike emoji which can be copied/paste to text, the icon is a svg image, so currently we are only able to add icon for specific scenes, may I ask where you want to use the icon specifically?

**Comment by neshorg** [comment]
That explains a lot. 

In my case I have a few areas where I'd like to use them, so I'll give an example with the screenshot below:
![image](https://user-images.githubusercontent.com/86983837/205932767-80112d4c-09cd-4233-9e3c-c7c773915813.png)
*As you can see, I've now used the standard windows emoji's in the dropdown & text components. 

I'm currently testing an app where I'd like to add the {{ "/icon:solid/Users" }} next to the string (text component) of 'Total users'. 
On the other hand I'd like to add icons to the dropdown menu as well to make things a little more interesting but also to make it more intuitive for the user to recognize the icons. 

For example, I could remove the "logout" button which would create more space in my header by placing an extra option below in the dropdown menu called "logout". Hence, here I'd then use the same icon I've used now on the actual logout button: {{ "/icon:solid/SignOutAlt" }}

**Comment by lmx1117** [comment]
This seems like a reasonable request, we will add icon to dropdown in next version, as for the text component, it can be a little complex and may take some time, please stay tuned😉

**Comment by neshorg** [comment]
Thank you for considering this request, I'm already happy with openblocks in general..so anything extra is much appreciated.
I will stay tuned 👍🏽

**Comment by agaitan026** [comment]
+1

**Comment by lmx1117** [comment]
Hi everyone, this issue is already solved, please check it out, and thanks again for your excellent advice and patience🤩

**Comment by neshorg** [comment]
Hello @lmx1117, being able to use the icons in the dropdown component is amazing!! 
I'm looking forward to seeing this in other components as well 😊
