### ISSUE TITLE
word-break in TextComponent

### ISSUE THREAD

**Issue by jmif** [openblocks-dev/openblocks#96]
Loving openblocks so far!  We're having an issue with the text component that I believe comes from [this line](https://github.com/openblocks-dev/openblocks/blob/1c5846d04987ffb113f4833e31786943a0cbd3a1/client/packages/openblocks/src/comps/comps/textComp.tsx#L65).

Text components have `word-break: break-all` set on them, which makes it difficult to read as a paragraph:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1000442/205943394-f9f3542e-6e7c-4754-a240-7afc95b20002.png">

With `word-break: break-word` applied via the dev console:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1000442/205943760-302adc79-b4f2-4ac6-a73d-bddde90fa6b3.png">

Would be great if we could make this configurable, I've searched for how to do it but haven't had any luck so far!

**Comment by neon-balcony** [comment]
Hi, this issue has been fixed and will be released this week. Please stay tuned:grinning:

**Comment by lmx1117** [comment]
Hi jmif, this issue is already solved, please check it out, and thanks again for your advice and patience. 😉
