### ISSUE TITLE
Option to Disable Spinner and Fade effect from Table Module

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#97]
In some cases we want to make our Table Module to constantly getting refreshed so that to show data in "real time".

Because of that we do not want the spinner wheel and fade effect to happen because it distracts the user.

It would be better to have an option to disable the spinner wheel and fade effect and just show the newest data as the table is getting refreshed without any loading effect.

**Comment by hanshuai** [comment]
Thanks for your report. We will add an option for table to disable loading effect.

**Comment by lmx1117** [comment]
Hi MichalisDBA, this issue is already solved, please check it out, and thanks again for your advice and patience.🤝

**Comment by MichalisDBA** [comment]
@lmx1117 Thank you very much. It works!
